In [322]:
import numpy as np
import pandas as pd
import re,ast
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [323]:
df = pd.read_csv('appartments.csv')

In [324]:
df.iloc[22]

PropertyName                PropertyName
PropertySubName          PropertySubName
NearbyLocations          NearbyLocations
LocationAdvantages    LocationAdvantages
Link                                Link
PriceDetails                PriceDetails
TopFacilities              TopFacilities
Name: 22, dtype: object

In [325]:
df=df.drop(22)

In [326]:
df.head()

                  PropertyName  ...                                      TopFacilities
0           Smartworld One DXP  ...  ['Swimming Pool', 'Salon', 'Restaurant', 'Spa'...
1                    M3M Crown  ...  ['Bowling Alley', 'Mini Theatre', 'Manicured G...
2  Adani Brahma Samsara Vilasa  ...  ['Terrace Garden', 'Gazebo', 'Fountain', 'Amph...
3                   Sobha City  ...  ['Swimming Pool', 'Volley Ball Court', 'Aerobi...
4     Signature Global City 93  ...  ['Mini Theatre', 'Doctor on Call', 'Concierge ...

[5 rows x 7 columns]

In [327]:
df.shape

(246, 7)

In [328]:
df.iloc[2].NearbyLocations

"['AIPL Business Club Sector 62', 'Heritage Xperiential Learning School', 'CK Birla Hospital', 'Paras Trinity Mall Sector 63', 'Rapid Metro Station Sector 56']"

In [329]:
df.iloc[2].LocationAdvantages

"{'AIPL Business Club Sector 62': '2.7 Km', 'Heritage Xperiential Learning School': '2 Km', 'CK Birla Hospital': '2.5 Km', 'Paras Trinity Mall Sector 63': '3.5 Km', 'Rapid Metro Station Sector 56': '3.8 Km', 'De Adventure Park': '6.8 Km', 'Golf Course Ext Rd': '99 Meter', 'DoubleTree by Hilton Hotel Gurgaon': '3.6 Km', 'KIIT College of Engineering Sohna Road': '8.4 Km', 'Mehrauli-Gurgaon Road': '11.8 Km', 'Indira Gandhi International Airport': '21.1 Km', 'Nirvana Rd': '160 Meter', 'TERI Golf Course': '8.7 Km'}"

In [330]:
df.iloc[1].PriceDetails

"{'3 BHK': {'building_type': 'Apartment', 'area_type': 'Super Built-up Area', 'area': '1,605 - 2,170 sq.ft.', 'price-range': '₹ 2.2 - 3.03 Cr'}, '4 BHK': {'building_type': 'Apartment', 'area_type': 'Super Built-up Area', 'area': '2,248 - 2,670 sq.ft.', 'price-range': '₹ 3.08 - 3.73 Cr'}}"

In [331]:
df.iloc[2].TopFacilities

"['Terrace Garden', 'Gazebo', 'Fountain', 'Amphitheatre', 'Party Lawn', 'Basketball Court', 'Badminton Court', 'Yoga/Meditation Area', 'Indoor Games']"

In [332]:
df[['PropertyName','TopFacilities']]

                    PropertyName                                      TopFacilities
0             Smartworld One DXP  ['Swimming Pool', 'Salon', 'Restaurant', 'Spa'...
1                      M3M Crown  ['Bowling Alley', 'Mini Theatre', 'Manicured G...
2    Adani Brahma Samsara Vilasa  ['Terrace Garden', 'Gazebo', 'Fountain', 'Amph...
3                     Sobha City  ['Swimming Pool', 'Volley Ball Court', 'Aerobi...
4       Signature Global City 93  ['Mini Theatre', 'Doctor on Call', 'Concierge ...
..                           ...                                                ...
242         DLF Princeton Estate  ['Swimming Pool', 'Medical Centre', 'Laundry',...
243        Pyramid Urban Homes 2  ['Shopping Centre', 'Community Hall', '24x7 Se...
244          Satya The Hermitage  ['Bus Shelter', 'Swimming Pool', 'Business Lou...
245                  BPTP Spacio  ['Swimming Pool', 'Card Room', 'Piped Gas', 'P...
246             SS The Coralwood  ['Swimming Pool', 'School', 'Solar Lighting', ...

[246 rows x 2 columns]

In [333]:
df[['PropertyName','TopFacilities']]['TopFacilities'][0]

"['Swimming Pool', 'Salon', 'Restaurant', 'Spa', 'Cafeteria', 'Sun Deck', '24x7 Security', 'Club House', 'Gated Community']"

In [334]:
def extract_list(s):
    return re.findall(r"'(.*?)'", s)

df['TopFacilities'] = df['TopFacilities'].apply(extract_list)

In [335]:
df[['PropertyName','TopFacilities']]['TopFacilities'][0]

['Swimming Pool',
 'Salon',
 'Restaurant',
 'Spa',
 'Cafeteria',
 'Sun Deck',
 '24x7 Security',
 'Club House',
 'Gated Community']

In [336]:
df['FacilitiesStr'] = df['TopFacilities'].apply(' '.join)

In [337]:
df['FacilitiesStr'][0]

'Swimming Pool Salon Restaurant Spa Cafeteria Sun Deck 24x7 Security Club House Gated Community'

In [338]:
tfidf_vectorizer = TfidfVectorizer(stop_words='english', ngram_range=(1, 2))

In [339]:
tfidf_matrix = tfidf_vectorizer.fit_transform(df['FacilitiesStr'])

In [340]:
tfidf_matrix.toarray()

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.14379378,
        0.14379378],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]], shape=(246, 953))

In [341]:
tfidf_matrix.toarray().shape

(246, 953)

In [342]:
tfidf_matrix.toarray()[0]

array([0.        , 0.        , 0.        , 0.18809342, 0.18809342,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.16873099, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.27811185, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.17445059, 0.17445059,
       0.15589841, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.16355699, 0.29372893, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.18084455, 0.18084455,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.17445059, 0.        , 0.24773259, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.06440364,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.2659983 , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.12932284, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.21010446, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.16522746,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.25610081, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.15177345,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.21412748, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.14918792,
       0.29372893, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.16355699, 0.16355699, 0.        ,
       0.        , 0.        , 0.06493586, 0.06493586, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        ])

In [343]:
cosine_sim1 = cosine_similarity(tfidf_matrix, tfidf_matrix)

In [344]:
cosine_sim1.shape

(246, 246)

In [345]:

def recommend_properties(property_name, cosine_sim=cosine_sim1):
    # Get the index of the property that matches the name
    idx = df.index[df['PropertyName'] == property_name].tolist()[0]

    # Get the pairwise similarity scores with that property
    sim_scores = list(enumerate(cosine_sim1[idx]))

    # Sort the properties based on the similarity scores
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)

    # Get the scores of the 10 most similar properties
    sim_scores = sim_scores[1:6]

    # Get the property indices
    property_indices = [i[0] for i in sim_scores]
    
    recommendations_df = pd.DataFrame({
        'PropertyName': df['PropertyName'].iloc[property_indices],
        'SimilarityScore': sim_scores
    })

    # Return the top 10 most similar properties
    return recommendations_df

In [346]:
recommend_properties("DLF The Arbour")

           PropertyName            SimilarityScore
64      Ace Palm Floors   (63, 0.4529382062441955)
217         Yashika 104  (216, 0.4199606322926784)
93       JMS The Nation   (92, 0.4166584649363288)
154       India Rashtra   (153, 0.398954234680194)
0    Smartworld One DXP   (0, 0.38885046199432893)

In [347]:
df[['PropertyName','PriceDetails']]

                    PropertyName                                       PriceDetails
0             Smartworld One DXP  {'2 BHK': {'building_type': 'Apartment', 'area...
1                      M3M Crown  {'3 BHK': {'building_type': 'Apartment', 'area...
2    Adani Brahma Samsara Vilasa  {'3 BHK': {'building_type': 'Independent Floor...
3                     Sobha City  {'2 BHK': {'building_type': 'Apartment', 'area...
4       Signature Global City 93  {'2 BHK': {'building_type': 'Independent Floor...
..                           ...                                                ...
242         DLF Princeton Estate  {'2 BHK': {'building_type': 'Apartment', 'area...
243        Pyramid Urban Homes 2  {'1 BHK': {'building_type': 'Apartment', 'area...
244          Satya The Hermitage  {'2 BHK': {'building_type': 'Apartment', 'area...
245                  BPTP Spacio  {'2 BHK': {'building_type': 'Apartment', 'area...
246             SS The Coralwood  {'2 BHK': {'building_type': 'Apartment', 'area...

[246 rows x 2 columns]

In [348]:
df[['PropertyName','PriceDetails']]['PriceDetails'][1]

"{'3 BHK': {'building_type': 'Apartment', 'area_type': 'Super Built-up Area', 'area': '1,605 - 2,170 sq.ft.', 'price-range': '₹ 2.2 - 3.03 Cr'}, '4 BHK': {'building_type': 'Apartment', 'area_type': 'Super Built-up Area', 'area': '2,248 - 2,670 sq.ft.', 'price-range': '₹ 3.08 - 3.73 Cr'}}"

In [349]:
import pandas as pd
import json

# Load the dataset
df_appartments = pd.read_csv('appartments.csv').drop(22)

# Function to parse and extract the required features from the PriceDetails column
def refined_parse_modified_v2(detail_str):
    try:
        details = json.loads(detail_str.replace("'", "\""))
    except:
        return {}

    extracted = {}
    for bhk, detail in details.items():
        # Extract building type
        extracted[f'building type_{bhk}'] = detail.get('building_type')

        # Parsing area details
        area = detail.get('area', '')
        area_parts = area.split('-')
        if len(area_parts) == 1:
            try:
                value = float(area_parts[0].replace(',', '').replace(' sq.ft.', '').strip())
                extracted[f'area low {bhk}'] = value
                extracted[f'area high {bhk}'] = value
            except:
                extracted[f'area low {bhk}'] = None
                extracted[f'area high {bhk}'] = None
        elif len(area_parts) == 2:
            try:
                extracted[f'area low {bhk}'] = float(area_parts[0].replace(',', '').replace(' sq.ft.', '').strip())
                extracted[f'area high {bhk}'] = float(area_parts[1].replace(',', '').replace(' sq.ft.', '').strip())
            except:
                extracted[f'area low {bhk}'] = None
                extracted[f'area high {bhk}'] = None

        # Parsing price details
        price_range = detail.get('price-range', '')
        price_parts = price_range.split('-')
        if len(price_parts) == 2:
            try:
                extracted[f'price low {bhk}'] = float(price_parts[0].replace('₹', '').replace(' Cr', '').replace(' L', '').strip())
                extracted[f'price high {bhk}'] = float(price_parts[1].replace('₹', '').replace(' Cr', '').replace(' L', '').strip())
                if 'L' in price_parts[0]:
                    extracted[f'price low {bhk}'] /= 100
                if 'L' in price_parts[1]:
                    extracted[f'price high {bhk}'] /= 100
            except:
                extracted[f'price low {bhk}'] = None
                extracted[f'price high {bhk}'] = None

    return extracted
# Apply the refined parsing and generate the new DataFrame structure
data_refined = []

for _, row in df_appartments.iterrows():
    features = refined_parse_modified_v2(row['PriceDetails'])
    
    # Construct a new row for the transformed dataframe
    new_row = {'PropertyName': row['PropertyName']}
    
    # Populate the new row with extracted features
    for config in ['1 BHK', '2 BHK', '3 BHK', '4 BHK', '5 BHK', '6 BHK', '1 RK', 'Land']:
        new_row[f'building type_{config}'] = features.get(f'building type_{config}')
        new_row[f'area low {config}'] = features.get(f'area low {config}')
        new_row[f'area high {config}'] = features.get(f'area high {config}')
        new_row[f'price low {config}'] = features.get(f'price low {config}')
        new_row[f'price high {config}'] = features.get(f'price high {config}')
    
    data_refined.append(new_row)

df_final_refined_v2 = pd.DataFrame(data_refined).set_index('PropertyName')

In [350]:
df_final_refined_v2

                            building type_1 BHK  area low 1 BHK  ...  price low Land  price high Land
PropertyName                                                     ...
Smartworld One DXP                         None             NaN  ...             NaN              NaN
M3M Crown                                  None             NaN  ...             NaN              NaN
Adani Brahma Samsara Vilasa                None             NaN  ...            2.05            41.13
Sobha City                                 None             NaN  ...             NaN              NaN
Signature Global City 93                   None             NaN  ...             NaN              NaN
...                                         ...             ...  ...             ...              ...
DLF Princeton Estate                       None             NaN  ...             NaN              NaN
Pyramid Urban Homes 2                 Apartment           335.0  ...             NaN              NaN
Satya The Hermitage                        None             NaN  ...             NaN              NaN
BPTP Spacio                                None             NaN  ...             NaN              NaN
SS The Coralwood                           None             NaN  ...             NaN              NaN

[246 rows x 40 columns]

In [351]:
df_final_refined_v2.columns

Index(['building type_1 BHK', 'area low 1 BHK', 'area high 1 BHK',
       'price low 1 BHK', 'price high 1 BHK', 'building type_2 BHK',
       'area low 2 BHK', 'area high 2 BHK', 'price low 2 BHK',
       'price high 2 BHK', 'building type_3 BHK', 'area low 3 BHK',
       'area high 3 BHK', 'price low 3 BHK', 'price high 3 BHK',
       'building type_4 BHK', 'area low 4 BHK', 'area high 4 BHK',
       'price low 4 BHK', 'price high 4 BHK', 'building type_5 BHK',
       'area low 5 BHK', 'area high 5 BHK', 'price low 5 BHK',
       'price high 5 BHK', 'building type_6 BHK', 'area low 6 BHK',
       'area high 6 BHK', 'price low 6 BHK', 'price high 6 BHK',
       'building type_1 RK', 'area low 1 RK', 'area high 1 RK',
       'price low 1 RK', 'price high 1 RK', 'building type_Land',
       'area low Land', 'area high Land', 'price low Land', 'price high Land'],
      dtype='object')

In [352]:
df_final_refined_v2.shape

(246, 40)

In [353]:
df['PriceDetails'][0]

"{'2 BHK': {'building_type': 'Apartment', 'area_type': 'Carpet Area', 'area': '1,370 sq.ft.', 'price-range': '₹ 2 - 2.4 Cr'}, '3 BHK': {'building_type': 'Apartment', 'area_type': 'Carpet Area', 'area': '1,850 - 2,050 sq.ft.', 'price-range': '₹ 2.25 - 3.59 Cr'}, '4 BHK': {'building_type': 'Apartment', 'area_type': 'Carpet Area', 'area': '2,600 sq.ft.', 'price-range': '₹ 3.24 - 4.56 Cr'}}"

In [354]:
df_final_refined_v2.iloc[0]

building type_1 BHK         None
area low 1 BHK               NaN
area high 1 BHK              NaN
price low 1 BHK              NaN
price high 1 BHK             NaN
building type_2 BHK    Apartment
area low 2 BHK            1370.0
area high 2 BHK           1370.0
price low 2 BHK              2.0
price high 2 BHK             2.4
building type_3 BHK    Apartment
area low 3 BHK            1850.0
area high 3 BHK           2050.0
price low 3 BHK             2.25
price high 3 BHK            3.59
building type_4 BHK    Apartment
area low 4 BHK            2600.0
area high 4 BHK           2600.0
price low 4 BHK             3.24
price high 4 BHK            4.56
building type_5 BHK         None
area low 5 BHK               NaN
area high 5 BHK              NaN
price low 5 BHK              NaN
price high 5 BHK             NaN
building type_6 BHK         None
area low 6 BHK               NaN
area high 6 BHK              NaN
price low 6 BHK              NaN
price high 6 BHK             NaN
building type_1 RK          None
area low 1 RK                NaN
area high 1 RK               NaN
price low 1 RK               NaN
price high 1 RK              NaN
building type_Land          None
area low Land                NaN
area high Land               NaN
price low Land               NaN
price high Land              NaN
Name: Smartworld One DXP, dtype: object

In [355]:
categorical_columns = df_final_refined_v2.select_dtypes(include=['object']).columns.tolist()

In [356]:
categorical_columns

['building type_1 BHK',
 'building type_2 BHK',
 'building type_3 BHK',
 'building type_4 BHK',
 'building type_5 BHK',
 'building type_6 BHK',
 'building type_1 RK',
 'building type_Land']

In [357]:
ohe_df = pd.get_dummies(df_final_refined_v2, columns=categorical_columns, drop_first=True)

In [358]:
ohe_df.fillna(0,inplace=True)

In [359]:
ohe_df

                             area low 1 BHK  area high 1 BHK  ...  building type_5 BHK_Villa  building type_6 BHK_Villa
PropertyName                                                  ...
Smartworld One DXP                      0.0              0.0  ...                      False                      False
M3M Crown                               0.0              0.0  ...                      False                      False
Adani Brahma Samsara Vilasa             0.0              0.0  ...                      False                      False
Sobha City                              0.0              0.0  ...                      False                      False
Signature Global City 93                0.0              0.0  ...                      False                      False
...                                     ...              ...  ...                        ...                        ...
DLF Princeton Estate                    0.0              0.0  ...                      False                      False
Pyramid Urban Homes 2                 335.0            398.0  ...                      False                      False
Satya The Hermitage                     0.0              0.0  ...                      False                      False
BPTP Spacio                             0.0              0.0  ...                      False                      False
SS The Coralwood                        0.0              0.0  ...                      False                      False

[246 rows x 43 columns]

In [360]:
from sklearn.preprocessing import StandardScaler

# Initialize the scaler
scaler = StandardScaler()

# Apply the scaler to the entire dataframe
ohe_df_normalized = pd.DataFrame(scaler.fit_transform(ohe_df), columns=ohe_df.columns, index=ohe_df.index)

In [361]:
ohe_df_normalized.head()

                             area low 1 BHK  area high 1 BHK  ...  building type_5 BHK_Villa  building type_6 BHK_Villa
PropertyName                                                  ...
Smartworld One DXP                -0.252266        -0.169584  ...                  -0.216353                  -0.063888
M3M Crown                         -0.252266        -0.169584  ...                  -0.216353                  -0.063888
Adani Brahma Samsara Vilasa       -0.252266        -0.169584  ...                  -0.216353                  -0.063888
Sobha City                        -0.252266        -0.169584  ...                  -0.216353                  -0.063888
Signature Global City 93          -0.252266        -0.169584  ...                  -0.216353                  -0.063888

[5 rows x 43 columns]

In [362]:
from sklearn.metrics.pairwise import cosine_similarity

# Compute the cosine similarity matrix
cosine_sim2 = cosine_similarity(ohe_df_normalized)

In [363]:
cosine_sim2.shape

(246, 246)

In [364]:
def recommend_properties_with_scores(property_name, top_n=247):
    
    # Get the similarity scores for the property using its name as the index
    sim_scores = list(enumerate(cosine_sim2[ohe_df_normalized.index.get_loc(property_name)]))
    
    # Sort properties based on the similarity scores
    sorted_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)
    
    # Get the indices and scores of the top_n most similar properties
    top_indices = [i[0] for i in sorted_scores[1:top_n+1]]
    top_scores = [i[1] for i in sorted_scores[1:top_n+1]]
    
    # Retrieve the names of the top properties using the indices
    top_properties = ohe_df_normalized.index[top_indices].tolist()
    
    # Create a dataframe with the results
    recommendations_df = pd.DataFrame({
        'PropertyName': top_properties,
        'SimilarityScore': top_scores
    })
    
    return recommendations_df

In [365]:
recommend_properties_with_scores('M3M Golf Hills')

                PropertyName  SimilarityScore
0    AIPL The Peaceful Homes         0.955462
1         Smartworld One DXP         0.954670
2             Unitech Escape         0.953092
3                M3M Capital         0.951156
4                 BPTP Terra         0.943128
..                       ...              ...
240              Golden Park        -0.522391
241      Satya Merano Greens        -0.523660
242       ROF Normanton Park        -0.525129
243          BPTP Green Oaks        -0.525286
244           JMS The Nation        -0.526287

[245 rows x 2 columns]

In [366]:
df[['PropertyName','LocationAdvantages']]

                    PropertyName                                 LocationAdvantages
0             Smartworld One DXP  {'Bajghera Road': '800 Meter', 'Palam Vihar Ha...
1                      M3M Crown  {'DPSG Palam Vihar Gurugram': '1.4 Km', 'The N...
2    Adani Brahma Samsara Vilasa  {'AIPL Business Club Sector 62': '2.7 Km', 'He...
3                     Sobha City  {'The Shikshiyan School': '2.9 KM', 'WTC Plaza...
4       Signature Global City 93  {'Pranavananda Int. School': '450 m', 'DLF Sit...
..                           ...                                                ...
242         DLF Princeton Estate  {'Sector 42-43 Metro Station': '1.8 Km', 'Para...
243        Pyramid Urban Homes 2  {'Aarvy Healthcare Super Speciality': '1.8 KM'...
244          Satya The Hermitage  {'Dwarka Expressway': '1.2 Km', 'S N Internati...
245                  BPTP Spacio  {'Suncity School': '0.2 Km', 'Gurugram Road': ...
246             SS The Coralwood  {'Sector 84 Road': '600 Meter', 'Delhi Public ...

[246 rows x 2 columns]

In [367]:
df[['PropertyName','LocationAdvantages']]['LocationAdvantages'][0]

"{'Bajghera Road': '800 Meter', 'Palam Vihar Halt': '2.5 KM', 'DPSG Palam Vihar': '3.1 KM', 'Park Hospital': '3.1 KM', 'Gurgaon Railway Station': '4.9 KM', 'The NorthCap University': '5.4 KM', 'Dwarka Expy': '1.2 KM', 'Hyatt Place Gurgaon Udyog Vihar': '7.7 KM', 'Dwarka Sector 21, Metro Station': '7.2 KM', 'Pacific D21 Mall': '7.4 KM', 'Indira Gandhi International Airport': '14.7 KM', 'Hamoni Golf Camp': '6.2 KM', 'Fun N Food Waterpark': '8.8 KM', 'Accenture DDC5': '9 KM'}"

In [368]:
def distance_to_meters(distance_str):
    try:
        if 'Km' in distance_str or 'KM' in distance_str:
            return float(distance_str.split()[0]) * 1000
        elif 'Meter' in distance_str or 'meter' in distance_str:
            return float(distance_str.split()[0])
        else:
            return None
    except:
        return None

In [369]:
location_matrix = {}

for _, row in df.iterrows():
    distances = {}

    for location, distance in ast.literal_eval(row['LocationAdvantages']).items():
        distances[location] = distance_to_meters(distance)

    location_matrix[row['PropertyName']] = distances

location_df = pd.DataFrame.from_dict(location_matrix, orient='index')

In [370]:
location_df.shape

(246, 1070)

In [371]:
print(location_df.columns.tolist())

['Bajghera Road', 'Palam Vihar Halt', 'DPSG Palam Vihar', 'Park Hospital', 'Gurgaon Railway Station', 'The NorthCap University', 'Dwarka Expy', 'Hyatt Place Gurgaon Udyog Vihar', 'Dwarka Sector 21, Metro Station', 'Pacific D21 Mall', 'Indira Gandhi International Airport', 'Hamoni Golf Camp', 'Fun N Food Waterpark', 'Accenture DDC5', 'DPSG Palam Vihar Gurugram', 'Park Hospital, Palam Vihar', 'Palam Vihar Halt Railway Station', 'Dwarka Sector 21 Metro Station', 'Dwarka Expressway', 'Fun N Food Water Park', 'Tau DeviLal Sports Complex', 'Hyatt Place', 'Altrade Business Centre', 'AIPL Business Club Sector 62', 'Heritage Xperiential Learning School', 'CK Birla Hospital', 'Paras Trinity Mall Sector 63', 'Rapid Metro Station Sector 56', 'De Adventure Park', 'Golf Course Ext Rd', 'DoubleTree by Hilton Hotel Gurgaon', 'KIIT College of Engineering Sohna Road', 'Mehrauli-Gurgaon Road', 'Nirvana Rd', 'TERI Golf Course', 'The Shikshiyan School', 'WTC Plaza', 'Luxus Haritma Resort', 'BSF Golf Course', 'Rions Hospital', 'Gurgaon', 'Dwarka Sector 21', 'Nehru Stadium', 'Fun N Food WaterPark', 'IGI Airport', 'Vasant Kunj', 'Pranavananda Int. School', 'DLF Site central office', 'Holiday Inn Gurugram Sector 90', 'Krishna Hospital', 'Royal Institute Of Science', 'Sapphire 83 Mall', 'NH48', 'Garhi Harsaru Junction', 'Manesar Golf Course', 'AapnoGhar', 'Vega Schools NH-8', 'DLF Corporate Greens', 'Miracles Apollo Cradle Hospital', 'Hyatt Regency Gurugram', 'NH 48', 'Golden Greens Golf & Resorts Limited', 'Mount Olympus Junior School', 'Miracles Apollo Hospital', 'NH -8', 'Savoy Suites, Manesar', 'Golden Greens Golf & Resorts', 'IMT Manesar', 'Amity University Gurugram', 'Golf Course Extension Road', 'Dwarka Expy, Sector 109', 'Euro International School, Sector- 109', 'Jai Sai Ram Hospital', 'Aryan Hospital', 'Idea Cosmic Plaza', 'Indira Gandhi Intl Airport', 'Royal Institute Of Science & Management', 'Pataudi Road', 'Holiday Inn Sector 90', 'RPS International School', 'Aarvy Healthcare Hospital', 'Iris Broadway Mall', 'Imperia Mindspace', 'AIPL Business Tower', 'Heritage School', 'Lotus Valley Intl School, Gurgaon', 'Gurugram University', 'Sector 55-56 Metro Station', 'Omaxe Gurgaon Mall', 'Sushant University', 'Badshahpur Sohna Rd Hwy,Sector 48', 'Naurangpur Cricket Stadium', 'Naurangpur Road', 'National Highway  48', 'Vatika Town Square-INXT', 'Ompee International School', 'Manesar Bus Stand', 'Yashlok Medical Centre', 'Euro International School', 'WorldMark Gurgaon', 'Capital Cyberscape', 'The Shriram Millennium School', 'DoubleTree by Hilton Hotel', 'Badshahpur Sohna Hwy', 'Nakhrola Stadium', 'Delhi - Jaipur Expressway', 'Vatika Town Square-INXT Mall', 'Savoy Suites', 'Bal Bharati Public School', 'Vatika Business Centre', 'Indira Gandhi Int. Airport', "St. Xavier's High School", 'Miracles Apollo Cradle', 'Ambience Mall New', 'NH8', 'Hyatt Regency Gurgaon', 'Delhi Public School', 'Elan Miracle Mall', 'Miracles Apollo Cradle Spectra Hospital', 'Agri Business Management Collage', 'Delhi Jaipur Expressway', 'Grand Hyatt Gurgaon', 'Duke Horse Riding Club', 'PVR Drive In Cinema', 'W Pratiksha Hospital', 'Metro World Mall', 'Unicosmos School', 'Faridabad Gurgaon Road', 'Sohna Road', 'Bestech Business Tower', 'Appu Ghar', 'SkyJumper Trampoline Park', 'Axis Bank', 'KMP Expressway', 'Karma Lakelands', 'Jungle Safari & Trails', 'DPS Manesar', 'Medanta Hospital', 'Faridabad - Gurgaon Road', "Lingaya's Lalita Devi Institute", 'ASF Insignia SEZ', 'Banjara Market Gurugram', 'Central Plaza Mall', 'Paras Hospitals, Gurgaon', 'Badshahpur Sohna Rd Hwy', 'Vega School', 'Indian School of Hospitality', 'Vatika City Centre', 'Aatish Hospital', 'Info Technology Park Phase 2', 'Huda Metro Station', 'Southern Peripheral Rd', 'Global Ways School', 'Radisson Hotel', 'NH 248A', 'Sector 55/56 Metro Station', 'Mavens Inn', 'Sanar International Hospital', 'Sector 53-54 Metro Station', 'IILM University, Gurugram', 'The Banyan Tree World School', 'The Big Tree Cafe', 'DLF Golf and Country Club', 'Delhi Public School, Sector 84', 'Aarvy Hospital', 'DPG Degree College', 'Shivani public school', 'Baghera University', 'Kutumbh Hospital', 'Bijwasan Railway Station', 'Global Foyer Mall', 'Phase 2 Metro Station', 'Gurgaon Dreamz Mall', 'Metro Hospital, Palam Vihar', 'Delhi Ajmer Expressway', 'Infinity Business Park', 'Huda metro station', "Rion's Hospital", 'Euro International School, Sector- 109.', 'Golf Course Ext Road', 'Heritage Xperiential Learning, CRPF Rd', 'Sector 54 Chowk Metro Station', 'Gurgaon - Delhi Expy', 'Genesis Hospital Sector 84', 'DPGITM Engineering College Sector 34', 'Sapphire 83 Mall Sector 83', 'Holiday Inn Hotel Sector 90', 'SkyJumper Trampoline Park Gurgaon', 'National Tennis Academy Sector 98', 'NH-8 Delhi Jaipur Highway', 'Nouveau Medics Multispeciality OPD', 'Heritage Village Resort & Spa', 'Sector 86 Road', 'Genesis Hospital', 'Delh-Ajmer Expy', 'DPG Institute of Technology', 'Medanta -The Medicity', 'Airia Mall', 'Amma Hospital', 'DPS International Edge', 'Eros City Square', 'Splendor Trade Tower', 'Narayana Junior College', 'Sector 55 Metro Station', 'Dharampur Main Road', "Oyster's Water Park", 'Vivanta Dwarka New Delhi', 'DLF Corporate Park', 'GD Goenka World School', 'KR Mangalam University', 'Smart View Hotel and Resort', 'Central Park Flower Valley', 'Shopping complex', 'Delhi Public School Sector 84', 'Central Peripheral Road', 'Nakhrola Stadium Sector 81A', 'NH 08', 'Imt Manesar', 'G D Goenka University', 'Fly India Adventure Resort', 'Vardaan Hospital', 'IMT Office Sohna', 'JMS Marine Square Mall', 'Vibrant Hospital', 'Prime Scholars Int. School', 'Ramgarh Farms & Resort', 'Basai Road', 'Shree Krishna Hospital', 'The Esplanade Mall', 'GEMS International School', 'Pranavananda International School', 'Greenway Hospital', 'National Tennis Academy', 'NH-8', 'Paras Trinity Mall', 'Rajesh Pilot Road', 'Scottish High International School', 'KIIT College of Engineering', 'The Vivekananda School', 'Southern Peripheral Road', 'Holiday Inn Express Gurugram Sector 50', 'Early Basket Grocery shop', 'Aradhya Cricket Club Gurgaon', 'Imperial Heritage School', 'Daultabad Village Park', 'Skylark Cricket Academy', 'Yashroop Hospital', 'Gurgaon Old Railway Station', "Domino's Pizza", 'Conscient One Mall', 'Emerald Plaza Shopping Mall', 'Pawlywoof - Dog Park', 'SCC Drive-In Cinema', 'Lemon Tree Hotel, Sohna Road', 'Shiksha Bharti Public School', 'Holiday Inn Express Gurugram', 'Sahara Mall', 'Dhanwapur Road', 'Govt. PG College', 'Basai Dhankot', 'Park Inn', 'IFFCO Chowk Metro Station', 'The Executive Centre', 'Dwarka Expy, Sector 88', 'Euro Int School, Sector 37D, Gurugram', 'Reliance Trends Newtown Square Mall', 'SGT University', 'Medanta-The Medicity', 'SGT Hospital 1', 'Suncity School', 'Green Field School', 'Narayana E Techno', 'Alpine Convent School', 'Little E Step –Pre School', 'Sheetla Mata Mandir', 'Captain Chandan Lal Marg', 'CD International School', 'Raheja Mall', 'Basai Dhankot Railway Station', 'First Step Play School', 'Sri Ma Montessori International', 'Dwaraka Expressway', 'Ansal Plaza', 'Proposed Metro Station', 'Delhi International Airport', 'KMP Corridor', 'Vega Schools Sector 48', 'Cloudnine Hospital Sector 47', 'PVR Drive In Theatre', 'City Hospital', 'NH 352W, Pataudi', 'Pathfinder Global School, Pataudi', 'Vistar Complex', 'BML Munjal University (BMU)', 'Sector 55-56 Metro station', 'Bestech Central Square Mall', 'ORCHIDS The International School', 'Marengo Asia Hospitals', 'Sector 42-43 Rapid Metro', 'Sector 53-54 Rapid Metro', 'Bank Of Baroda', 'HDFC Bank ATM', 'Muincipal Corporation of Gurugram', 'One Horizon Center Bus Stop', 'Shalom Hills International School', 'Satyam Medicare Hospital', 'Anand Preschool', 'Choice pharmacy', 'Qutub Plaza', 'Sunset point', 'EPF Regional Office', 'IFFCO Chowk', 'Kingdom of Dreams', 'Gaytri Public School', 'KIIT College', 'SPM Hospital', 'Sealdah Railway Station', 'International Airport', 'Lemon Tree Hotel', 'CK Birla Hospital, Gurgaon', 'Golf Pavilion', 'Golf Course Road', 'Ardee Mall', 'Shiv Nadar School', 'NH 148A', 'Ambience Public School', 'Heritage Intl Xperiential School', 'Summer Fields School', 'Primamed Super Speciality Hospital', 'Uma Sanjeevani Health Centre', 'Anya Gurgaon', 'Hotel Golf View Suites', 'Apollo Pharmacy', 'Rx Pharmacy', 'Sector 42/43 Bus Stand', 'Genpact Chowk Bus Stop', 'Huda City Centre Metro Station', 'Sector 53 Metro Station', 'ICICI Bank ATM', 'Bharat Petroleum Retail Outlet', 'DLF Linear Park', 'Le Meridien Gurgaon', 'Sector 42-43 Metro Station', 'Faridabad - Gurgaon Rd', 'Ambience Mall', 'Fun N Food Village', 'F9 Go Karting Gurgaon', 'Proposed Metro corridor', 'N.H-8', 'Shiskshantar', 'DPS', 'Amity', 'Pathways', 'GD Goenka', 'Medicity', 'Artemis', 'Max, Fortis', 'Apollo', 'Paras Trinity Shopping Mall', 'Swastik Multispeciality Hospital', 'AIPL Business Co Working Space', 'Lemon Tree Hotel Sector 60', 'MKD Hospital', 'PVR Drive in Theatre', 'Sant Soordas Sihi Metro Station', 'De Adventure Amusement Park', 'Vatika Business Park Sector 49', 'Suncity School, Sector 37D', 'The Signature Advanced Super Speciality', 'Gurugram University Kankrola', 'Candor TechSpace, Sector 48', 'IndusInd Bank ATM', "Cherub's Cradle", 'Mavens Orange - Hotel', 'Learning Stars School', 'State Bank of India', 'Deerika HyperMart', 'Triangular Park', 'Artimis hospital', 'Sector 45 SO Post Office', 'FUEL NATION', 'HSBC', 'Women Police Station', 'Best IVF Centre', 'Huda City Centre', 'Gurugram Public School', 'Shikshantar - Primary School', 'Mamta Hospital', 'IG International Airport', 'Omaxe City Centre', 'DLF Grand Mall', 'Arvy Hospital', 'Matrikiran School', 'DLF Cyber City', 'Vatika Town Square', 'Global city centre', 'Sohna road dhunela', 'Gd goenka university', 'Vardaan hospital and trauma centre', 'Maharana pratap school', 'Sector 55-56 metro', 'Garhi harsaru railway station Gurgaon', 'HUB 66', 'Sealdah', 'Sector 55-56 Rapid Metro Station', 'Hasanpur', 'The Oberoi', 'Euro Intl School, Sector- 109', 'Najafgarh Kapashera Road', 'Dwarka Sector 21 Metro station', 'Hong Kong Bazaar', 'Bharti International Convent School', 'Badshahpur Sohna Rd Hwy, Sector 68', 'Ashoka International School', 'The Oberoi Gurgaon', 'GD Goenka Public School', 'Chauma Road', 'Chirag Hospital', 'Sector-21 Metro Dwarka', 'AIPL Joy Street Mall', 'Radisson Hotel Sohna Road', 'iON Digital Zone (Gurugram)', 'HUDA Mini Golf Course', 'IMT Road', 'National Highway 48', 'Sohna Gurgaon Road', 'Spaze Itech Park', 'Pallavan PreSchool, Sohna Road', 'Radisson Hotel Gurugram Sohna Road', 'Polaris Hospital', 'RBSM Public school', 'Health Care Pharmacy', 'Sector 54 Chowk', 'EuroKids Preschool Suncity', 'YES Bank ATM', 'Suncity School Gurgaon', 'Suncity Shopping Complex', 'Vallores Pre School', 'Umkal Hospital', 'Haryana City Gas', 'Marigold Secondary School', 'Alpine Hospital', 'Pushpanjali Hospital', 'Golf Course Extension Rd', 'Country Inn', 'Westin', 'The Millenium School', 'Rajiv Chowk - Sohna Highway', 'KMP corridor', 'Central Park Resorts', 'GD Goenka University', 'Swastik Hospital Sec 66', 'Adarsh Senior Secondary School', 'Golf Course Extension', 'International Tech Park Gurgaon,', 'Sector 55-56 Metro', 'Surajgarh Gurgaon, Golf Course Ext Rd', 'Ananta Hospital', 'Indus World School', 'Golf Corse Ext. Rd.', 'National Highway-48', 'Prime Scholars International School', 'Dwarka Expy, Dhanwapur Village', 'Shri Balaji’s Multispeciality Hospital', 'Euro International School, Sector 37D', 'Delhi Public School, Sector 103', 'Park Inn, Gurgaon', 'DLF World Tech Park', 'Star Mall', 'The Hive Shopping Mall', 'NH-8, IMT Manesar', 'Yaduvanshi Shiksha Niketan', 'Royal Institute Of Science and Mgt', 'Newtown Square Mall', 'NH 352W', 'Eros Corporate Park', 'Manesar Road', 'Euro International School, Sec 84', 'Huda Metro Station (Gurugram)', 'InfinityS Badminton Academy', 'Sanskar Bharti Public School', 'Manipal Hospital, Gurugram', 'HUDA Market, Sector 14', 'Delhi Gurgaon Expressway', 'SCC Rooftop Drive-In', 'The Oberoi, Gurgaon', 'Gurugram Railway Station', 'Kings International School', 'HUDA Market', 'Basai Metro Station', 'CBR Cricket Ground', 'Rapid Metro Sector 55-56', 'Kunskapsskolan School', 'Omaxe Celebration Mall', 'Gurgaon - Delhi Expy, Sector 75A', 'International Tech Park Gurgaon', 'Shalom Presidency School', 'Sector 55-56 Rapid Metro', 'Jinga Lala Theme Park Gurgaon Delhi', 'Pataudi Rd, Sector 95B', 'RELIANCE TRENDS Newtown Square Mall', 'Aarvy Healthcare Super Speciality', 'Approved Sector 37 Mero Station', 'Signature Hospital', 'Xavier’s International', 'Alpine School', 'Esplanade Mall', 'Sector 10 Market', 'Blue Bells Public School', 'infinity Business Park', 'Medanta The Medicity', 'Galleria 108 Mall', 'Manipal Hospital', 'Vivanta New Delhi, Dwarka', 'Bharat Ram Global School', 'Canara Bank ATM', 'Yes Bank', 'Arc Hospital', 'Canara Bank', 'Axis Bank ATM', 'City Square', 'Shishu Kalyan School', 'Rathore IMT Hospital', 'DSD College', 'Patil Station', 'Amity University', 'ICFAI University', 'Indira Gandhi Airport', 'Sapphire 83', 'Cambridge Montessori', 'Hyatt Regency', 'Rao Bharat Singh International School', 'Aarvy Healthcare', 'NH-8, Imt Manesar', 'Aapno Ghar', 'Cambridge College Of Education', 'Iffco Chowk', 'Euro International School, Sector 84', 'Dharampeth Main Road', 'Gurgaon railway station', 'Dwarka sector 21 metro station', 'Old Delhi Gurgaon Road', 'Rotary Public School', 'Candor Techspace', 'Manipal Hospital, Palam Vihar', 'Moulsari Avenue', 'Adarsh public school,Garhi Harsaru', 'PHC Garhi Harsaru', 'Excellere World School', 'Aman Hospital & Surgical Centre', 'Neemrana Palace', 'K. R. Mangalam University', 'Global City Centre', 'Vishwas Hospital', 'Ibis Hotel', 'Horizon 1 Mall', 'Sector 42-43 Metro station', 'Ernst & Young', 'Paras Hospital', 'Gurgaon Faridabad Highway', 'Mount Olympus School, Sec 79', 'Singhania University, Manesar', 'Capital Business Park', 'Old Sohna Dhani Road', 'GD Goenka Signature School', 'Vardaan Hospital & Trauma Centre', 'Public Bazar', 'GD Goenka School', 'Vatika Business Park', 'Bharat Petrol Pump', 'The Millennium School', 'IndusInd Bank', 'Artemis Hospital', 'Tau Devi Lal Sports Complex', 'Children Park', 'Medanta Dialysis Center', 'Central Park, Sohna Rd', 'HDFC Bank ATM, Dhunela Ghamroj', 'Ashiana Anmol  Kid Centric Homes', 'Indianoil, Sohna - Gurgaon Rd', 'Taj Hotel & Family Restaurant', 'V-Square Sohna New Residential', 'G D Goenka World School', 'The Phoenix Project, Sohna - Gurgaon Rd', 'Signature Global Park', 'Signum 36', 'Kotak Mahindra Bank, MBS Tower', 'Pasco Automobiles, Alipur, Sohna', 'Sohna Bus Stand', 'Imperio School', 'Ektaa Hospitals', 'Vipul Trade Business Centre', 'Radisson Hotel Gurugram', 'Airia Mall Sector 68', 'Damdama More', 'Civil Hospital', 'K.R. Mangalam University', 'Western Peripheral Expressway', 'Bhondsi Nature Park', 'Enkays Hospital', 'Lemon Tree Hotel,', 'Ram Krishna Public School', 'Aravalli Hill View Point', 'Gurugram Global Heights School', 'Satya The Hive Mall', 'Gurugram Road', 'The Signature Super Speciality Hospital', 'Sunrise University', 'Country Inn & Suites by Radisson', 'Yonex Badminton Stadium', 'Grand Hyatt', 'Au Grand Air', 'Indira Gandhi Eye Hospital', 'Double Tree by Hilton', 'Swastik Hospital', 'Jinaglala Theme Park', 'Scottish International School', 'Ap Sports cricket ground', 'Nischay Cricket Academy', 'DLC Cricket Ground', 'Drona Sports Village', 'Ramada by Wyndham Gurgaon', 'Mehrauli-Gurgaon Rd', 'Surajgarh Gurgaon', 'Apex Plus Hospital', 'ZEN Golf Range & Academy', 'The Banyan Tree Hiking Area', 'MG Road', 'Plaza Mall', 'MGF Metropolitan Mall', 'Lancers International School', 'Gurjar Samrat Jaipal Khatana Marg', 'Signature Global Infinity Mall Sohna', 'Vidya Niketan Sr Sec School', 'Sanjivani Hospital', 'Spectra Hospital', 'Golf Course Extn Road', 'Tulip Violet Society, Sector 69', 'Spaze Palazo, Golf Course Ext Rd', 'Federal Bank Sector 71', 'Kunskapsskolan International', 'Southern Peripheral Rd, Gurugram', 'Ektaa Hospitals  Main Sohna Rd', 'Central Bank Of India Sohna Rd', 'Sanjeevani Hospital - Child Specialist', 'VATIKA BUSINESS PARK Sohna Rd', 'IndianOil, Hasanpur', 'The Medicity, Spaze iTech Park', 'Axis Bank, Sohna Rd', 'Shambhu Dayal High School', 'Global City Centre Mall', 'Vardaan Hospital and Trauma Centre', 'Ascendas OneHub Gurgaon', 'IRIS Broadway Mall', 'Flying Wings Badminton Academy', 'Saraswati Model School', 'Orchid Business Park', 'Farrukh Nagar Railway Station', 'Medanta - The Medicity', 'M3m 65th Avenue Mall', 'DPS International School', 'Rapid Metro Sector 56', 'Sneh Hospital', 'Gems International School', 'National Highway 8', 'Appu Ghar Water Park', 'Tennis Vidyalaya (Tennis Academy)', 'Zooper India Trampoline Park', 'Teri Golf Course', 'Park Dr, DLF Phase 5', 'Paras Hospitals', 'Heritage badminton academy', 'Green Field Public School', 'Kadipur Industrial Area', 'Spazedge IT Park', 'JMD Megapolis', 'Sapphire Mall', 'More Hypermart , Vipul business park', 'Basant Valley Global School', 'The Paras World School', 'Vipul Trade Centre', 'WorldMark Gurgaon, Maidawas Rd', 'Artemis Hospital Gurgaon', 'Western Peripheral Expy, Gurugram', 'Raghunath Bal Vidya Mandir School', 'ESIC Hospital', 'S N International School', 'Infinitys Badminton Academy', 'Country Inn and Suites by Radisson', 'Sector 29 Gurgaon Pubs and Bars', 'Emaar Business Park', 'Southern Peripheral Rd, Dhani', 'Omaxe City Centre Mall', 'Badshahpur Sohna Rd Hwy, Malibu Town', 'Ektaa Hospital', "St. Xavier's School", 'PVR Drive In Theater', 'American Express', 'IDFC FIRST Bank', 'Sector 42-43', 'Sector 53-54', 'MGF Megacity Mall', 'Fortis hospital', 'Pataudi road', 'Dwarka expressway', 'Double Infinity market', 'Bamroli Cricket Ground', 'Aman Hospital', 'Kidzee', 'Paras Trinity', 'Golf course extension road', 'AIPL Business Club', 'Sector 55-56 rapid metro station', 'Narayana e-Techno School - Manesar', 'HDFC Bank, Pataudi Rd', 'SS Omnia, Sector 86', 'Canara Bank - Nawada Fatehpur', 'ICICI Bank ATM, Sector 86', 'Silver Streak Multi Speciality', 'RHM Public School', 'Minda Industries Nawada Fatehpur', 'Numberdar market, IMT Manesar', "Sodhi's Supermarket, Sector 82", 'M3M SCO Shop cum Office', 'Sector 42-43 Rapid Metro Station', 'Quality Inn Gurgaon', 'Minda Industries Limited', 'Central Park II Road', 'Omex City Centre Mall', 'Damdama Lake Rd', 'Sohna Hill Viewpoint', 'KR Mangalam University Sohna', 'Country Inn & Suites By Radisson', 'Hero Honda Chowk', 'Jagdish Super Market', 'Gyaananda School', 'Bharat Petroleum Shree Shyam Filling', 'The Club, International City', 'Conscient One', 'ICICI BANK ATM, Annapurna MKT', 'ESIC Dispensary', 'Canara Bank New Palam Vihar', 'Dwarka', 'Radha Krishan Mandir', 'Daultabad Stadium', 'Gurgaon Gramin Bank', 'IGIA Airport', 'SCR Model School', 'Golden Tulip Suites Gurgaon', 'South point Mall', 'Pathways School Gurgaon', 'Kidzee Sec-93', 'Jhankar Group of Institutions', 'Heritage Badminton Academy', 'Dwarka Expy/Northern Peripheral Rd', 'Dwarka expressway Basai crossing', 'Euro Intl School, Sector 37D, Gurugram', 'Sethi Hospital', 'HDFC Bank', 'The Sixth Element School', 'K.R.Mangalam World School', 'Sushil Park', 'Peer Baba Ki Mazar', 'Punjab National Bank', 'CoNexus.Life B35', 'Medhaam Pre School & Daycare', 'Moksh Wellness Pvt Ltd.', 'Marriott Courtyard', 'World Tech Park', 'Athena', 'Bharat Petroleum Petrol Pump', 'Sanskar Jyoti School', 'Arc Multi Speciality Hospital', 'NH-48', 'Narayana e Techno School', 'Medeor Hospital, Manesar', "Guls' Kitchen", 'The Nook', 'Open Tap', 'Frescos', 'Subway', 'BOB ATM', 'PNB ATM', 'HDFC bank ATM', 'YES bank ATM', 'Citibank ATM', 'Gurugram Hospital', 'Govind Hospital', 'Manish Gallexie 91', 'Silver Streak Multi Speciality Hospital', 'Holiday Inn Gurugram', 'NH-8 IMT Manesar', 'Airport', 'Vatika Sector Road', 'Gurugram University Sector 87', 'CNG Petrol Pump', 'Miracles Apollo Cradle/Spectra Hospital', 'Vivek Model School', 'Dwarka Expressway Link Road', "McDonald's India 

In [372]:
#finding near-duplicates columns
from collections import defaultdict
import re

def normalize(name):
    return re.sub(r'[^a-z0-9]', '', name.lower())

groups = defaultdict(list)

for col in location_df.columns:
    groups[normalize(col)].append(col)

duplicates = {k: v for k, v in groups.items() if len(v) > 1}

for v in duplicates.values():
    print(v)

['Gurgaon Railway Station', 'Gurgaon railway station']
['Dwarka Sector 21, Metro Station', 'Dwarka Sector 21 Metro Station', 'Dwarka Sector 21 Metro station', 'Dwarka sector 21 metro station']
['Fun N Food Waterpark', 'Fun N Food Water Park', 'Fun N Food WaterPark']
['Dwarka Expressway', 'Dwarka expressway']
['Tau DeviLal Sports Complex', 'Tau Devi Lal Sports Complex']
['TERI Golf Course', 'Teri Golf Course']
['Rions Hospital', "Rion's Hospital"]
['NH48', 'NH 48', 'NH-48']
['AapnoGhar', 'Aapno Ghar']
['NH -8', 'NH8', 'NH-8', 'N.H-8', 'NH 8']
['IMT Manesar', 'Imt Manesar']
['Golf Course Extension Road', 'Golf course extension road']
['Euro International School, Sector- 109', 'Euro International School, Sector- 109.']
['Pataudi Road', 'Pataudi road']
['Iris Broadway Mall', 'IRIS Broadway Mall']
['Sector 55-56 Metro Station', 'Sector 55/56 Metro Station', 'Sector 55-56 Metro station', 'Sector 55-56 metro station']
['Omaxe Gurgaon Mall', 'OMAXE Gurgaon Mall']
['National Highway  48', 'National Highway 48', 'National Highway-48']
['Delhi - Jaipur Expressway', 'Delhi Jaipur Expressway']
['Miracles Apollo Cradle Spectra Hospital', 'Miracles Apollo Cradle/Spectra Hospital', 'Miracles Apollo Cradle /Spectra Hospital']
['Faridabad Gurgaon Road', 'Faridabad - Gurgaon Road']
['Huda Metro Station', 'Huda metro station', 'HUDA Metro Station', 'Huda Metro station']
['NH 248A', 'NH 248 A', 'NH248A']
['Sector 53-54 Metro Station', 'Sector 53/54 Metro Station']
['Delhi Public School, Sector 84', 'Delhi Public School Sector 84']
['Infinity Business Park', 'infinity Business Park']
['Medanta -The Medicity', 'Medanta-The Medicity', 'Medanta The Medicity', 'Medanta - The Medicity']
['GD Goenka World School', 'G D Goenka World School']
['KR Mangalam University', 'K. R. Mangalam University', 'K.R. Mangalam University']
['G D Goenka University', 'Gd goenka university', 'GD Goenka University']
['GEMS International School', 'Gems International School']
['Park Inn', 'Park inn']
['IFFCO Chowk Metro Station', 'Iffco Chowk Metro Station']
['Reliance Trends Newtown Square Mall', 'RELIANCE TRENDS Newtown Square Mall']
['SGT University', 'SGT UNIVERSITY']
['KMP Corridor', 'KMP corridor']
['PVR Drive In Theatre', 'PVR Drive in Theatre']
['HDFC Bank ATM', 'HDFC bank ATM']
['IFFCO Chowk', 'Iffco Chowk']
['Lemon Tree Hotel', 'Lemon Tree Hotel,']
['Sector 42-43 Metro Station', 'Sector 42-43 Metro station']
['Global city centre', 'Global City Centre']
['Vardaan hospital and trauma centre', 'Vardaan Hospital and Trauma Centre']
['Sector 55-56 metro', 'Sector 55-56 Metro']
['HUB 66', 'Hub 66']
['Sector 55-56 Rapid Metro Station', 'Sector 55-56 rapid metro station']
['The Oberoi Gurgaon', 'The Oberoi, Gurgaon']
['Health Care Pharmacy', 'Health care pharmacy']
['YES Bank ATM', 'YES bank ATM']
['International Tech Park Gurgaon,', 'International Tech Park Gurgaon']
['NH-8, IMT Manesar', 'NH-8, Imt Manesar', 'NH-8 IMT Manesar']
['InfinityS Badminton Academy', 'Infinitys Badminton Academy']
['Yes Bank', 'YES Bank']
['Canara Bank', 'CANARA BANK']
['Country Inn & Suites by Radisson', 'Country Inn & Suites By Radisson']
['Heritage badminton academy', 'Heritage Badminton Academy']
['ESIC Hospital', 'ESIC HOSPITAL']
['Matrikiran High School', 'MatriKiran High School']
['Shiv Mandir', 'shiv Mandir']

In [373]:
#finding similar columns
from rapidfuzz import fuzz
import re

# ---------- Normalize ----------
def normalize(name):
    name = name.lower()
    replacements = {
        r'\bexpy\b': 'expressway',
        r'\bextn\b': 'extension',
        r'\bext\b': 'extension',
        r'\brd\b': 'road',
        r'\bintl\b': 'international',
        r'\bint\.\b': 'international',
        r'\bstn\b': 'station',
        r'&': 'and'
    }
    for old, new in replacements.items():
        name = re.sub(old, new, name)
    # remove punctuation
    name = re.sub(r'[^a-z0-9 ]', ' ', name)
    # remove extra spaces
    name = re.sub(r'\s+', ' ', name).strip()
    return name

# ---------- Extract Numbers ----------
def extract_numbers(text):
    return re.findall(r'\d+', text)

# ---------- Detect Similar Columns ----------
columns = location_df.columns.tolist()

visited = set()
similar_groups = []
for i, col1 in enumerate(columns):
    if col1 in visited:
        continue
    group = [col1]
    norm1 = normalize(col1)
    nums1 = extract_numbers(norm1)

    for j in range(i + 1, len(columns)):
        col2 = columns[j]
        if col2 in visited:
            continue
        norm2 = normalize(col2)
        nums2 = extract_numbers(norm2)
        
        # Numbers must match
        if nums1 != nums2:
            continue
        score = fuzz.token_sort_ratio(norm1, norm2)
        if score >= 92:
            group.append(col2)
    if len(group) > 1:
        similar_groups.append(group)
        visited.update(group)

# ---------- Print ----------
for g in similar_groups:
    print(g)

['Gurgaon Railway Station', 'Gurgaon Old Railway Station', 'Gurgaon railway station']
['Dwarka Expy', 'Dwarka Expressway', 'Dwaraka Expressway', 'Dwarka expressway']
['Dwarka Sector 21, Metro Station', 'Dwarka Sector 21 Metro Station', 'Dwarka Sector 21 Metro station', 'Dwarka sector 21 metro station']
['Indira Gandhi International Airport', 'Indira Gandhi Intl Airport']
['Fun N Food Waterpark', 'Fun N Food WaterPark']
['Tau DeviLal Sports Complex', 'Tau Devi Lal Sports Complex']
['Golf Course Ext Rd', 'Golf Course Extension Road', 'Golf Course Ext Road', 'Golf Course Extension Rd', 'Golf Corse Ext. Rd.', 'Golf Course Extn Road', 'Golf course extension road']
['Mehrauli-Gurgaon Road', 'Mehrauli-Gurgaon Rd']
['TERI Golf Course', 'Teri Golf Course']
['Rions Hospital', "Rion's Hospital"]
['IGI Airport', 'IGIA Airport']
['AapnoGhar', 'Aapno Ghar']
['NH 48', 'NH-48']
['NH -8', 'NH-8', 'NH 8']
['IMT Manesar', 'Imt Manesar']
['Euro International School, Sector- 109', 'Euro International School, Sector- 109.', 'Euro Intl School, Sector- 109']
['Pataudi Road', 'Pataudi road', 'Pataudi Rd']
['Iris Broadway Mall', 'IRIS Broadway Mall']
['Sector 55-56 Metro Station', 'Sector 55/56 Metro Station', 'Sector 55-56 Metro station', 'Sector 55-56 metro station']
['Omaxe Gurgaon Mall', 'OMAXE Gurgaon Mall']
['National Highway  48', 'National Highway 48', 'National Highway-48']
['Delhi - Jaipur Expressway', 'Delhi Jaipur Expressway']
["St. Xavier's High School", 'St Xavier High School']
['Miracles Apollo Cradle Spectra Hospital', 'Miracles Apollo Cradle/Spectra Hospital', 'Miracles Apollo Cradle /Spectra Hospital']
['Faridabad Gurgaon Road', 'Faridabad - Gurgaon Road', 'Faridabad - Gurgaon Rd']
['Sohna Road', 'Sohna Rd']
['Huda Metro Station', 'Huda metro station', 'HUDA Metro Station', 'Huda Metro station']
['Southern Peripheral Rd', 'Southern Peripheral Road', 'Southern Periphery Road']
['NH 248A', 'NH 248 A', 'NH 248']
['Sector 53-54 Metro Station', 'Sector 53/54 Metro Station']
['Delhi Public School, Sector 84', 'Delhi Public School Sector 84']
['Aarvy Hospital', 'Arvy Hospital']
['Delhi Ajmer Expressway', 'Delh-Ajmer Expy']
['Infinity Business Park', 'infinity Business Park']
['Gurgaon - Delhi Expy', 'Delhi Gurgaon Expressway']
['Medanta -The Medicity', 'Medanta-The Medicity', 'Medanta The Medicity', 'Medanta - The Medicity']
['Amma Hospital', 'Aman Hospital']
['Vivanta Dwarka New Delhi', 'Vivanta New Delhi, Dwarka']
['GD Goenka World School', 'G D Goenka World School']
['KR Mangalam University', 'K. R. Mangalam University', 'K.R. Mangalam University']
['G D Goenka University', 'Gd goenka university', 'GD Goenka University']
['GEMS International School', 'Gems International School']
['Scottish High International School', 'Scottish International School']
['Holiday Inn Express Gurugram Sector 50', 'Holiday Inn Express Gurugram Sec 50']
['Park Inn', 'Park inn']
['IFFCO Chowk Metro Station', 'Iffco Chowk Metro Station']
['Reliance Trends Newtown Square Mall', 'RELIANCE TRENDS Newtown Square Mall']
['SGT University', 'SGT UNIVERSITY']
['CD International School', 'DPS International School']
['Basai Dhankot Railway Station', 'Basai Dhancourt Railway Station']
['Proposed Metro Station', 'Propose Metro Station']
['KMP Corridor', 'KMP corridor']
['PVR Drive In Theatre', 'PVR Drive in Theatre', 'PVR Drive In Theater']
['HDFC Bank ATM', 'HDFC bank ATM']
['IFFCO Chowk', 'Iffco Chowk']
['International Airport', 'IG International Airport']
['Lemon Tree Hotel', 'Lemon Tree Hotel,']
['Golf Course Road', 'Golf Course Rd']
['Sector 42-43 Metro Station', 'Sector 42-43 Metro station']
['Artimis hospital', 'Artemis Hospital']
['Huda City Centre', 'Huda city center']
['Global city centre', 'Global City Centre']
['Vardaan hospital and trauma centre', 'Vardaan Hospital & Trauma Centre', 'Vardaan Hospital and Trauma Centre']
['Sector 55-56 metro', 'Sector 55-56 Metro']
['HUB 66', 'Hub 66']
['Sector 55-56 Rapid Metro Station', 'Sector 55-56 rapid metro station', 'Rapid Metro Station Sector 55 56']
['The Oberoi Gurgaon', 'The Oberoi, Gurgaon']
['Health Care Pharmacy', 'Health care pharmacy']
['YES Bank ATM', 'YES bank ATM']
['The Millenium School', 'The Millennium School']
['International Tech Park Gurgaon,', 'International Tech Park Gurgaon']
['NH-8, IMT Manesar', 'NH-8, Imt Manesar', 'NH-8 IMT Manesar']
['Euro International School, Sec 84', 'Euro International School, Sector 84']
['InfinityS Badminton Academy', 'Infinitys Badminton Academy']
['Kings International School', 'S N International School']
['Rapid Metro Sector 55-56', 'Sector 55-56 Rapid Metro']
['Yes Bank', 'YES Bank']
['Canara Bank', 'CANARA BANK']
['Paras Hospital', 'Paras Hospitals']
['Ektaa Hospitals', 'Ektaa Hospital']
['Gurugram Road', 'Gurugram Rd']
['The Signature Super Speciality Hospital', 'Signature Super Speciality Hospital']
['Country Inn & Suites by Radisson', 'Country Inn and Suites by Radisson', 'Country Inn & Suites By Radisson']
['Heritage badminton academy', 'Heritage Badminton Academy']
['ESIC Hospital', 'ESIC HOSPITAL']
['Omaxe City Centre Mall', 'Omex City Centre Mall']
['Matrikiran High School', 'MatriKiran High School']
['Shiv Mandir', 'shiv Mandir']
['Euro Intl School Sec-51', 'Euro International School, sector- 51']

In [374]:
# Merge duplicate columns

for group in duplicates.values():

    # Skip if some columns were already removed
    group = [c for c in group if c in location_df.columns]

    if len(group) < 2:
        continue

    # Choose canonical name
    canonical = max(group, key=len)

    # Merge (minimum distance)
    location_df[canonical] = location_df[group].min(axis=1)

    # Drop remaining columns
    location_df.drop(columns=[c for c in group if c != canonical],
                     inplace=True)

print("Duplicate columns merged.")

Duplicate columns merged.

In [375]:
# Merge similar columns

for group in similar_groups:

    # Some columns may already have been dropped
    group = [c for c in group if c in location_df.columns]

    if len(group) < 2:
        continue

    # Choose canonical name
    canonical = max(group, key=len)

    # Merge (minimum distance)
    location_df[canonical] = location_df[group].min(axis=1)

    # Drop remaining columns
    location_df.drop(columns=[c for c in group if c != canonical],
                     inplace=True)

print("Similar columns merged.")

Similar columns merged.

In [376]:
location_df.shape

(246, 945)

In [377]:
location_df

                            Bajghera Road  Palam Vihar Halt  ...  Sector 84 Road  Skyview Corporate Park
Smartworld One DXP                  800.0            2500.0  ...             NaN                     NaN
La Vida by Tata Housing             550.0               NaN  ...             NaN                     NaN
Oxirich Chintamanis                5300.0               NaN  ...             NaN                     NaN
Rishali Luxe Residency 112         1500.0               NaN  ...             NaN                     NaN
Emaar Digihomes                       NaN               NaN  ...             NaN                     NaN
...                                   ...               ...  ...             ...                     ...
The Close South                       NaN               NaN  ...             NaN                     NaN
DLF New Town Heights 2                NaN               NaN  ...             NaN                     NaN
DLF New Town Heights 1                NaN               NaN  ...             NaN                     NaN
Antriksh Heights                      NaN               NaN  ...             NaN                     NaN
BPTP Freedom Park Life                NaN               NaN  ...             NaN                     NaN

[246 rows x 945 columns]

In [378]:
location_df.fillna(54000,inplace=True) #cannot replace by 0 as they are distances and if NaN replaced by very large no

In [379]:
from sklearn.preprocessing import StandardScaler
# Initialize the scaler
scaler = StandardScaler()

# Apply the scaler to the entire dataframe
location_df_normalized = pd.DataFrame(scaler.fit_transform(location_df), columns=location_df.columns, index=location_df.index)

In [380]:
location_df_normalized

                            Bajghera Road  Palam Vihar Halt  ...  Sector 84 Road  Skyview Corporate Park
Smartworld One DXP              -7.960979        -15.652476  ...        0.063888                0.063888
La Vida by Tata Housing         -7.998993          0.063888  ...        0.063888                0.063888
Oxirich Chintamanis             -7.276720          0.063888  ...        0.063888                0.063888
Rishali Luxe Residency 112      -7.854539          0.063888  ...        0.063888                0.063888
Emaar Digihomes                  0.128476          0.063888  ...        0.063888                0.063888
...                                   ...               ...  ...             ...                     ...
The Close South                  0.128476          0.063888  ...        0.063888                0.063888
DLF New Town Heights 2           0.128476          0.063888  ...        0.063888                0.063888
DLF New Town Heights 1           0.128476          0.063888  ...        0.063888                0.063888
Antriksh Heights                 0.128476          0.063888  ...        0.063888                0.063888
BPTP Freedom Park Life           0.128476          0.063888  ...        0.063888                0.063888

[246 rows x 945 columns]

In [381]:
cosine_sim3 = cosine_similarity(location_df_normalized)

In [382]:
cosine_sim3.shape

(246, 246)

In [383]:
def recommend_properties_with_scores(property_name, top_n=247):
    
    # Get the similarity scores for the property using its name as the index
    sim_scores = list(enumerate(cosine_sim3[location_df_normalized.index.get_loc(property_name)]))
    
    # Sort properties based on the similarity scores
    sorted_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)
    
    # Get the indices and scores of the top_n most similar properties
    top_indices = [i[0] for i in sorted_scores[1:top_n+1]]
    top_scores = [i[1] for i in sorted_scores[1:top_n+1]]
    
    # Retrieve the names of the top properties using the indices
    top_properties = location_df_normalized.index[top_indices].tolist()
    
    # Create a dataframe with the results
    recommendations_df = pd.DataFrame({
        'PropertyName': top_properties,
        'SimilarityScore': top_scores
    })
    
    return recommendations_df

In [384]:
recommend_properties_with_scores('BPTP Terra')

                            PropertyName  SimilarityScore
0                AIPL The Peaceful Homes         0.129436
1                             M3M Merlin         0.103459
2                           Tulip Yellow         0.101208
3            Bestech Park View Sanskruti         0.092462
4    International City by SOBHA Phase 2         0.090292
..                                   ...              ...
240                    Ansal API Esencia        -0.054233
241                      The Close South        -0.054233
242               DLF New Town Heights 2        -0.054233
243                     Antriksh Heights        -0.054233
244               BPTP Freedom Park Life        -0.054233

[245 rows x 2 columns]

In [385]:
3*cosine_sim3 + 5*cosine_sim2 + 6*cosine_sim1

array([[14.        ,  1.19133255,  0.21727255, ...,  1.2212103 ,
         0.75505959,  1.79359813],
       [ 1.19133255, 14.        ,  1.06887686, ..., -0.73456689,
        -0.78415277, -0.74611071],
       [ 0.21727255,  1.06887686, 14.        , ..., -0.7856021 ,
        -1.95023916, -1.61287042],
       ...,
       [ 1.2212103 , -0.73456689, -0.7856021 , ..., 14.        ,
         1.30266004,  1.29813121],
       [ 0.75505959, -0.78415277, -1.95023916, ...,  1.30266004,
        14.        ,  7.81050775],
       [ 1.79359813, -0.74611071, -1.61287042, ...,  1.29813121,
         7.81050775, 14.        ]], shape=(246, 246))

In [386]:
def recommend_properties_with_scores(property_name, top_n=247):

    cosine_sim_matrix = 30 * cosine_sim1 + 20 * cosine_sim2 + 8 * cosine_sim3
    
    # Get the similarity scores for the property using its name as the index
    sim_scores = list(enumerate(cosine_sim_matrix[location_df_normalized.index.get_loc(property_name)]))
    
    # Sort properties based on the similarity scores
    sorted_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)
    
    # Get the indices and scores of the top_n most similar properties
    top_indices = [i[0] for i in sorted_scores[1:top_n+1]]
    top_scores = [i[1] for i in sorted_scores[1:top_n+1]]
    
    # Retrieve the names of the top properties using the indices
    top_properties = location_df_normalized.index[top_indices].tolist()
    
    # Create a dataframe with the results
    recommendations_df = pd.DataFrame({
        'PropertyName': top_properties,
        'SimilarityScore': top_scores
    })
    
    return recommendations_df

In [387]:
recommend_properties_with_scores('BPTP Terra')

                   PropertyName  SimilarityScore
0       Lion Infra Green Valley        22.179061
1            Pegasus Atulyam 83        21.481893
2            Ireo The Corridors        19.999230
3             Conscient Habitat        19.023959
4    Bestech Park View Spa Next        18.681379
..                          ...              ...
240          Emaar Palm Gardens        -9.048380
241                 M3M Skywalk        -9.233710
242           Vatika Aspiration        -9.293958
243               Orchid Petals        -9.533701
244                  M3M Natura       -10.196694

[245 rows x 2 columns]

In [395]:
import pickle
pickle.dump(location_df,open('location_distance.pkl','wb'))

In [396]:
pickle.dump(cosine_sim1, open('cosine_sim1.pkl', 'wb'))
pickle.dump(cosine_sim2, open('cosine_sim2.pkl', 'wb'))
pickle.dump(cosine_sim3, open('cosine_sim3.pkl', 'wb'))

In [400]:
apartment_link=df[['PropertyName','Link']]

In [401]:
pickle.dump(apartment_link,open('apartment_link.pkl','wb'))