In [102]:
import numpy as np
import pandas as pd

In [103]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [104]:
df = pd.read_csv('gurgaon_properties.csv')

In [105]:
df.sample(5)

,property_name,property_type,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
3028,3 BHK Flat in Gwal Pahari,flat,suncity vatsal valley,1.53,10699.0,1430.0,Carpet area: 1430 (132.85 sq.m.),3,3,3,not available,"Gwal Pahari, Gurgaon, Haryana",2.0,North-East,0 to 1 Year Old,"['Sector 55-56 Metro Station', 'Banjara Market...",Nestled in the green belt of aravallis\nNear g...,"['3 Wardrobe', '3 Fan', '1 Exhaust Fan', '3 Ge...","['Security / Fire Alarm', 'Power Back-up', 'Fe...",NaN
2584,2 BHK Flat in Sector 74 Gurgaon,flat,m3m skywalk,1.57,11000.0,1427.0,Super Built up area 1424(132.29 sq.m.)Built Up...,2,2,3+,others,"T1-1111, Sector 74 Gurgaon, Gurgaon, Haryana",10.0,South,1 to 5 Year Old,"['Omaxe Gurgaon Mall', 'Omaxe Celebration Mall...",M3m skywalk is one of gurgaon's most sought af...,NaN,"['Centrally Air Conditioned', 'Security / Fire...",NaN
603,3 BHK Flat in Nirvana Country,flat,the close north,2.75,12500.0,2200.0,Super Built up area 2605(242.01 sq.m.)Built Up...,3,3,3,servant room,"221, Nirvana Country, Gurgaon, Haryana",3.0,South-East,5 to 10 Year Old,"['Sector 55-56 Metro Station', 'Eros City Squa...","Power back up, lift, rain water harvesting, cl...",NaN,"['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Green Area5 out of 5', 'Construction4 out of..."
609,3 BHK Flat in Sector 71 Gurgaon,flat,chd avenue,1.15,6526.0,1762.0,Super Built up area 1762(163.7 sq.m.)Carpet ar...,3,3,2,servant room,"Sector 71 Gurgaon, Gurgaon, Haryana",15.0,East,5 to 10 Year Old,"['Huda City Centre', 'Apna Mart', 'Rajiv Chowk...",Top floor of 15th floor building\nBedrooms::3 ...,"['3 Wardrobe', '5 Fan', '3 Geyser', '5 Light',...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Management2 out of 5', 'Green Area5 out of 5..."
1374,2 BHK Flat in Sector-5 Sohna,flat,mvn athens sohna gurgaon,0.28,5833.0,480.0,Carpet area: 480 (44.59 sq.m.),2,2,1,not available,"Sector-5 Sohna, Gurgaon, Haryana",2.0,NaN,1 to 5 Year Old,NaN,"Near to dam dama lake, lush green and 3km away...",NaN,"['Feng Shui / Vaastu Compliant', 'Security / F...",NaN

In [106]:
df.shape

(3961, 20)

In [107]:
df.duplicated().sum()

np.int64(0)

In [108]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3961 entries, 0 to 3960
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    3961 non-null   object
 1   property_type    3961 non-null   object
 2   society          3960 non-null   object
 3   price            3941 non-null   float64
 4   price_per_sqft   3941 non-null   float64
 5   area             3941 non-null   float64
 6   areaWithType     3961 non-null   object
 7   bedRoom          3961 non-null   int64
 8   bathroom         3961 non-null   int64
 9   balcony          3961 non-null   object
 10  additionalRoom   3961 non-null   object
 11  address          3950 non-null   object
 12  floorNum         3940 non-null   float64
 13  facing           2784 non-null   object
 14  agePossession    3960 non-null   object
 15  nearbyLocations  3754 non-null   object
 16  description      3961 non-null   object
 17  furnishDetails   2929 non-null   object
 18  features         3252 non-null   object
 19  rating           3511 non-null   object
dtypes: float64(4), int64(2), object(14)
memory usage: 619.0+ KB

In [109]:
df.isnull().sum()

property_name         0
property_type         0
society               1
price                20
price_per_sqft       20
area                 20
areaWithType          0
bedRoom               0
bathroom              0
balcony               0
additionalRoom        0
address              11
floorNum             21
facing             1177
agePossession         1
nearbyLocations     207
description           0
furnishDetails     1032
features            709
rating              450
dtype: int64

In [110]:
df.head()

,property_name,property_type,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,5 Bedroom House for sale in Sector 11 Gurgaon,house,independent,4.00,19753.0,2025.0,Built Up area: 225 (188.13 sq.m.)Carpet area: ...,5,4,1,not available,"Sector 11, Sector 11 Gurgaon, Gurgaon, Haryana",2.0,North-East,undefined,"['Palam Vihar Vyapar kendra', 'Palam triangle'...","4 bath, furnished, overlooking garden/park, ma...","['1 Wardrobe', '1 Fan', '1 Light', 'No AC', 'N...",NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
1,3 BHK Flat in Sector 32 Gurgaon,flat,aqua front towers,2.50,11715.0,2134.0,Built Up area: 2134 (198.26 sq.m.),3,4,3,not available,"Sohna Sector 32, Sector 32 Gurgaon, Gurgaon, H...",1.0,NaN,undefined,NaN,Multistorey apartment is available for sale. I...,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,NaN
2,4 BHK Flat in Sector 110 Gurgaon,flat,indiabulls enigma,3.30,9850.0,3350.0,Super Built up area 3350(311.23 sq.m.),4,5,3,servant room,"N/a, Sector 110 Gurgaon, Gurgaon, Haryana",7.0,East,1 to 5 Year Old,"['Dwarka Sector 21 Metro Station', 'Gurgaon Dr...",Located in the popular residential address of ...,[],"['Security / Fire Alarm', 'Power Back-up', 'Fe...","['Environment4 out of 5', 'Lifestyle4 out of 5..."
3,3 BHK Flat in Sector 104 Gurgaon,flat,puri emerald bay,2.30,9387.0,2450.0,Super Built up area 2450(227.61 sq.m.),3,4,3+,servant room,"N/a, Sector 104 Gurgaon, Gurgaon, Haryana",10.0,North-East,5 to 10 Year Old,"['Sector-21 Metro Dwarka', 'Gurgaon Dreamz Mal...",This 3 bhk apartment is available for sale in ...,[],"['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Green Area5 out of 5', 'Construction5 out of..."
4,4 Bedroom House for sale in Nirvana Country,house,nirvana cedar crest,3.99,8866.0,4500.0,Plot area 4500(418.06 sq.m.),4,5,3+,"pooja room,servant room","Nirvana Country, Gurgaon, Haryana",4.0,North-East,0 to 1 Year Old,"['Radhakrishna Shani Mandir', 'Standard charte...",This is an newly constructed villa located in ...,"['4 Geyser', '9 Light', '1 AC', '1 Modular Kit...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle5 out of 5..."

In [111]:
df.insert(loc=3,column='sector',value=df['property_name'].str.split('in').str.get(1).str.replace('Gurgaon','').str.strip())

In [112]:
df.head()

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,5 Bedroom House for sale in Sector 11 Gurgaon,house,independent,Sector 11,4.00,19753.0,2025.0,Built Up area: 225 (188.13 sq.m.)Carpet area: ...,5,4,1,not available,"Sector 11, Sector 11 Gurgaon, Gurgaon, Haryana",2.0,North-East,undefined,"['Palam Vihar Vyapar kendra', 'Palam triangle'...","4 bath, furnished, overlooking garden/park, ma...","['1 Wardrobe', '1 Fan', '1 Light', 'No AC', 'N...",NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
1,3 BHK Flat in Sector 32 Gurgaon,flat,aqua front towers,Sector 32,2.50,11715.0,2134.0,Built Up area: 2134 (198.26 sq.m.),3,4,3,not available,"Sohna Sector 32, Sector 32 Gurgaon, Gurgaon, H...",1.0,NaN,undefined,NaN,Multistorey apartment is available for sale. I...,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,NaN
2,4 BHK Flat in Sector 110 Gurgaon,flat,indiabulls enigma,Sector 110,3.30,9850.0,3350.0,Super Built up area 3350(311.23 sq.m.),4,5,3,servant room,"N/a, Sector 110 Gurgaon, Gurgaon, Haryana",7.0,East,1 to 5 Year Old,"['Dwarka Sector 21 Metro Station', 'Gurgaon Dr...",Located in the popular residential address of ...,[],"['Security / Fire Alarm', 'Power Back-up', 'Fe...","['Environment4 out of 5', 'Lifestyle4 out of 5..."
3,3 BHK Flat in Sector 104 Gurgaon,flat,puri emerald bay,Sector 104,2.30,9387.0,2450.0,Super Built up area 2450(227.61 sq.m.),3,4,3+,servant room,"N/a, Sector 104 Gurgaon, Gurgaon, Haryana",10.0,North-East,5 to 10 Year Old,"['Sector-21 Metro Dwarka', 'Gurgaon Dreamz Mal...",This 3 bhk apartment is available for sale in ...,[],"['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Green Area5 out of 5', 'Construction5 out of..."
4,4 Bedroom House for sale in Nirvana Country,house,nirvana cedar crest,Nirvana Country,3.99,8866.0,4500.0,Plot area 4500(418.06 sq.m.),4,5,3+,"pooja room,servant room","Nirvana Country, Gurgaon, Haryana",4.0,North-East,0 to 1 Year Old,"['Radhakrishna Shani Mandir', 'Standard charte...",This is an newly constructed villa located in ...,"['4 Geyser', '9 Light', '1 AC', '1 Modular Kit...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle5 out of 5..."

In [113]:
df['sector'] = df['sector'].str.lower()

In [114]:
df['sector'].value_counts()

sector
sohna                                                        163
sector 102                                                   113
sector 85                                                    110
sector 92                                                    104
sector 69                                                     94
sector 90                                                     90
sector 65                                                     90
sector 81                                                     90
sector 109                                                    88
sector 79                                                     80
sector 83                                                     69
sector 37d                                                    68
sector 86                                                     67
sector 104                                                    66
sector 107                                                    60
sector 108                                                    59
sector 56                                                     57
sector 95                                                     57
sector 89                                                     56
sector 48                                                     56
sector 70a                                                    54
nirvana country                                               53
sector 70                                                     53
sector 37c                                                    53
sector 84                                                     51
sector-33 sohna                                               51
palam vihar                                                   50
sector 67                                                     48
sector 66                                                     46
sector 103                                                    45
dlf phase 1                                                   43
sector 113                                                    43
dlf phase 2                                                   43
sector 82                                                     42
sector 61                                                     42
sector 106                                                    38
sector 49                                                     36
sector 99a                                                    32
sushant lok phase 1                                           31
sector 68                                                     30
sector 72                                                     29
sector 77                                                     29
sector 54                                                     27
laxman vihar                                                  27
sector 71                                                     27
dlf phase 4                                                   26
sector 112                                                    24
sector 88a                                                    23
sector 33                                                     23
dlf phase 3                                                   22
sector 67a                                                    22
sector 111                                                    22
sector 22                                                     20
sector 82a                                                    20
sector 78                                                     19
sector 74                                                     18
sector 63a                                                    18
sector 62                                                     17
sector 91                                                     17
sector 110                                                    16
sector 99                                                     16
sushant lok phase 3                                           16
sector 60                                                     15
sector 14                                                     15
sector 63                                                     15
sector 1 imt manesar                                          14
sector 53                                                     14
sector 52                                                     14
gwal pahari                                                   14
sector 76                                                     14
rajendra park                                                 14
sector 3                                                      14
dlf phase 5                                                   14
laxman vihar phase 2                                          13
sector 36a                                                    13
sector 46                                                     13
uppals southend                                               12
sector 31                                                     12
sector 50                                                     12
sector 93                                                     12
sector 38                                                     12
sector 39                                                     12
sohna road                                                    12
sector 9a                                                     11
ashok vihar phase 3 extension                                 11
sector 47                                                     11
sector 1a imt manesar                                         10
sector 7                                                      10
sector 55                                                      9
sector 95a                                                     9
south city 1                                                   9
sector 4                                                       9
ashok vihar phase 2                                            9
c block sushant lok phase 1                                    8
sector 43                                                      8
sector 89 a                                                    8
mehrauli  road                                                 8
palam vihar extension                                          8
sector 59                                                      8
dwarka expressway                                              8
sector 57                                                      8
sector 10a                                                     8
malibu town                                                    8
sector 40                                                      8
new colony                                                     7
sector 51                                                      7
mianwali colony                                                7
sector 36 sohna                                                7
sector 26                                                      7
sector 11                                                      7
surat nagar 1                                                  7
sector 58                                                      7
jacobpura                                                      6
jyoti park                                                     6
rajiv nagar                                                    6
sector 5                                                       6
ashok vihar                                                    6
sector 1                                                       6
new palam vihar                                                5
sushant lok phase 2                                            5
manesar                                                        5
sector 2                                                       5
subhash nagar                                                  5
ansal plaza                                                    5
dayanand colony                                                5
saraswati vihar                                                5
arjun nagar                                                    5
sector 105                                                     5
sector 23a                                                     5
sector 28                                                      5
greenwood city                                                 5
sector 30                                                      5
chakkarpur                                                     5
sector 80                                                      5
sector 9                                                       5
vishnu garden                                                  4
valley view estate                                             4
sector 12                                                      4
sector 12a                                                     4
sector 45                                                      4
baldev nagar                                                   4
suncity                                                        4
devilal colony                                                 4
shivpuri                                                       4
bhondsi                                                        4
bhim nagar                                                     4
new                                                            4
sector 36                                                      4
ravi nagar                                                     4
adarsh nagar                                                   4
krishna colony                                                 4
sector 17                                                      4
sector 3a                                                      4
dharam colony                                                  4
shivaji nagar                                                  4
sector 6                                                       4
madanpuri                                                      4
garhi harsaru                                                  4
imt manesar                                                    4
surya vihar                                                    4
shakti nagar                                                   3
b block sushant lok phase 1                                    3
sector 88b                                                     3
sector 17a                                                     3
sector 23                                                      3
sector 27                                                      3
sector 17b                                                     3
sector 110 a                                                   3
sector 73                                                      3
a block sushant lok phase 1                                    3
maruti kunj                                                    3
laxmi garden                                                   3
prem nagar                                                     3
gandhi nagar                                                   3
mg road                                                        3
sector 15                                                      3
sector 8                                                       3
patel nagar                                                    3
sohna  road                                                    2
block a surya vihar                                            2
sheetla colony                                                 2
shanti nagar                                                   2
lajpat nagar                                                   2
sector-2 sohna                                                 2
rajiv chowk                                                    2
mohan nagar                                                    2
acharya puri                                                   2
sector 24                                                      2
farukhnagar                                                    2
new palam vihar phase 2                                        2
samaspur                                                       2
bhawani enclave                                                2
faridabad road                                                 2
new basti                                                      2
, delhi ncr                                                    2
sector 32                                                      2
west rajiv nagar                                               2
mayfield garden                                                2
daulatabad                                                     2
sector 15 part 2                                               2
surat nagar phase 2                                            2
rosewood                                                       2
iffco chowk                                                    2
ambience island                                                2
golf course ext road                                           2
hira nagar                                                     2
new palam vihar phase 1                                        2
nars                                                           2
bissar                                                         2
surat nagar                                                    2
sushant lok                                                    2
pratap nagar                                                   2
golf course road                                               2
sector-11 sohna                                                2
sector 41                                                      2
sector 15 part 1                                               2
manohar nagar                                                  2
sector 21                                                      2
shankar vihar                                                  2
sispal vihar                                                   2
damdma                                                         1
ram nagar                                                      1
sadar bazar                                                    1
sector 42                                                      1
sai kunj                                                       1
urban estate, sector 5                                         1
khandsa                                                        1
south city                                                     1
sector 37b                                                     1
g block dlf city phase 1                                       1
sec 3 bhim vihar part 1 bhimgher kheri                         1
begampur khatola                                               1
hno 13 sagar enclave sura                                      1
ansal's palam vihar                                            1
sector 13                                                      1
udyog vihar phase 1                                            1
kanahi                                                         1
new colony, sector 7                                           1
kheri                                                          1
ats marigold                                                   1
old delhi road, opp sector-14                                  1
naharpur rupa                                                  1
pataudi road                                                   1
near nand hospital                                             1
near sector 1 market                                           1
tekchand nagar                                                 1
bhimgarh kheri phase 3                                         1
lucknow                                                        1
gopal nagar, garhi ghasita, sonipat                            1
new jyoti park                                                 1
sector 4 urban estate                                          1
carterpuri village                                             1
civil l                                                        1
ravi nager basai road                                          1
om nagar                                                       1
laxmna vihar, phase 2                                          1
mahavir pura                                                   1
b1 block sector 57                                             1
nirvana country pocket h                                       1
devi lal colony gali no 12 gurgaon nr omkar public school      1
ashok vihar phase 3                                            1
garauli kalan                                                  1
anand garden, sector-105                                       1
laxman vihar, railway road,                                    1
sector 17c                                                     1
sector-7 hous                                                  1
bptp                                                           1
park view                                                      1
saroop garden rajendra park                                    1
block h ashok vihar phase iii extension                        1
vir nagar                                                      1
sultanpur                                                      1
near khandsa road                                              1
saraswati enclave                                              1
sector 9b                                                      1
hsiidc plot sector 1 imt manesar                               1
sector-5 sohna                                                 1
godrej aria , sector 79 ,                                      1
huda saraswati vihar                                           1
heritage city                                                  1
mahalaxmi garden, rajendra place                               1
block g sector-57                                              1
cyber city                                                     1
sector 21a faridabad                                           1
alipur                                                         1
ashok vihar phase i                                            1
rajiv colony                                                   1
v block dlf phase 3                                            1
dhankot                                                        1
sector 5 chowk                                                 1
jacobpura near sadar bazar                                     1
shivji park colony                                             1
near pataudi chowk                                             1
near euro                                                      1
sector-35 sohna                                                1
part 3 sector 5                                                1
jat colony,fazilpur/taj nagar road                             1
rattan garden                                                  1
sector-5 sheetla colony                                        1
bhora kalan                                                    1
sector 37a                                                     1
Name: count, dtype: int64

In [115]:
df[~df['sector'].str.contains('sector')]['sector'].unique()

array(['nirvana country', 'sushant lok phase 3', 'acharya puri',
       'shivpuri', 'garauli kalan', 'dlf phase 1', 'near pataudi chowk',
       'sohna', 'new palam vihar', 'saraswati vihar', 'dlf phase 5',
       'palam vihar', 'baldev nagar', 'nars', 'jacobpura', 'mg road',
       'surat nagar 1', 'gwal pahari', 'laxman vihar phase 2',
       'patel nagar', 'sushant lok phase 1', 'dlf phase 2', 'dlf phase 4',
       'dwarka expressway', 'rajiv nagar', 'ashok vihar', 'dlf phase 3',
       'rajiv chowk', 'madanpuri', 'huda saraswati vihar',
       'garhi harsaru', 'mehrauli  road', 'c block sushant lok phase 1',
       'ravi nagar', 'south city 1', 'ashok vihar phase 2',
       'greenwood city', 'uppals southend', 'block a surya vihar',
       'block h ashok vihar phase iii extension', 'mayfield garden',
       'bhawani enclave', 'civil l', 'sheetla colony', 'dharam colony',
       'shivaji nagar', 'damdma', 'surya vihar', 'near khandsa road',
       'imt manesar', 'malibu town', 'bhora kalan', 'subhash nagar',
       'dayanand colony', 'sushant lok', 'bissar', 'khandsa',
       'laxman vihar', 'hira nagar', 'ashok vihar phase 3 extension',
       'suncity', 'new palam vihar phase 1', 'arjun nagar', 'sohna road',
       'alipur', 'manohar nagar', 'rajendra park',
       'jacobpura near sadar bazar', 'shivji park colony',
       'vishnu garden', 'rattan garden', 'new colony', 'maruti kunj',
       'cyber city', 'new', 'b block sushant lok phase 1', 'bptp',
       'vir nagar', 'pratap nagar', 'manesar', 'golf course road',
       'sushant lok phase 2', 'golf course ext road',
       'palam vihar extension', 'a block sushant lok phase 1',
       'sultanpur', 'shankar vihar', 'ansal plaza', 'sispal vihar',
       'surat nagar', 'ambience island', 'surat nagar phase 2',
       'laxmi garden', 'mianwali colony', 'krishna colony',
       'shanti nagar', 'ashok vihar phase 3', 'lajpat nagar',
       'jyoti park', 'bhim nagar', 'heritage city', 'farukhnagar',
       'bhondsi', 'faridabad road', 'saraswati enclave', 'iffco chowk',
       'adarsh nagar', 'daulatabad', 'devilal colony',
       'saroop garden rajendra park', 'park view', 'rosewood',
       'shakti nagar', 'laxman vihar, railway road,',
       'mahalaxmi garden, rajendra place', 'samaspur', 'sohna  road',
       'prem nagar', 'gandhi nagar', 'west rajiv nagar',
       'jat colony,fazilpur/taj nagar road', ', delhi ncr', 'near euro',
       'new basti', 'new palam vihar phase 2', 'dhankot',
       'v block dlf phase 3', 'rajiv colony', 'ashok vihar phase i',
       'chakkarpur',
       'devi lal colony gali no 12 gurgaon nr omkar public school',
       'kanahi', 'udyog vihar phase 1', "ansal's palam vihar",
       'hno 13 sagar enclave sura', 'begampur khatola',
       'sec 3 bhim vihar part 1 bhimgher kheri', 'valley view estate',
       'ram nagar', 'south city', 'mohan nagar', 'sai kunj',
       'sadar bazar', 'kheri', 'g block dlf city phase 1', 'ats marigold',
       'naharpur rupa', 'nirvana country pocket h', 'mahavir pura',
       'laxmna vihar, phase 2', 'om nagar', 'ravi nager basai road',
       'carterpuri village', 'new jyoti park',
       'gopal nagar, garhi ghasita, sonipat', 'lucknow',
       'bhimgarh kheri phase 3', 'tekchand nagar', 'near nand hospital',
       'pataudi road'], dtype=object)

In [116]:
len(df[~df['sector'].str.contains('sector')]['sector'].unique())

160

In [117]:
sector_map = {

    # Nirvana / Sushant Lok
    'nirvana country': 'sector 50',
    'nirvana country pocket h': 'sector 50',

    'sushant lok': 'sector 43',
    'sushant lok phase 1': 'sector 43',
    'a block sushant lok phase 1': 'sector 43',
    'b block sushant lok phase 1': 'sector 43',
    'c block sushant lok phase 1': 'sector 43',
    'sushant lok phase 2': 'sector 55',
    'sushant lok phase 3': 'sector 57',

    # DLF
    'dlf phase 1': 'sector 26',
    'g block dlf city phase 1': 'sector 26',
    'dlf phase 2': 'sector 25',
    'dlf phase 3': 'sector 24',
    'v block dlf phase 3': 'sector 24',
    'dlf phase 4': 'sector 28',
    'dlf phase 5': 'sector 53',

    # South City
    'south city': 'sector 40',
    'south city 1': 'sector 41',

    # Popular Townships
    'greenwood city': 'sector 45',
    'malibu town': 'sector 47',
    'mayfield garden': 'sector 51',
    'uppals southend': 'sector 49',
    'suncity': 'sector 54',
    'rosewood': 'sector 49',
    'heritage city': 'sector 25',

    # Palam Vihar
    'palam vihar': 'sector 23',
    "ansal's palam vihar": 'sector 23',
    'palam vihar extension': 'sector 23',
    'new palam vihar': 'sector 110',
    'new palam vihar phase 1': 'sector 110',
    'new palam vihar phase 2': 'sector 111',

    # Commercial
    'cyber city': 'sector 24',
    'ambience island': 'sector 24',
    'udyog vihar phase 1': 'sector 20',

    # Roads
    'dwarka expressway': 'sector 102',
    'golf course road': 'sector 42',
    'golf course ext road': 'sector 58',
    'sohna road': 'sector 48',
    'sohna  road': 'sector 48',
    'mg road': 'sector 28',
    'mehrauli  road': 'sector 14',
    'faridabad road': 'sector 65',
    'pataudi road': 'sector 10',
    'near pataudi chowk': 'sector 10',

    # Localities
    'maruti kunj': 'sector 59',
    'bhondsi': 'sector 79',
    'gwal pahari': 'sector 2',
    'valley view estate': 'sector 56',
    'kanahi': 'sector 45',
    'sispal vihar': 'sector 49',

    # Villages / Areas
    'khandsa': 'sector 37',
    'near khandsa road': 'sector 37',
    'daulatabad': 'sector 106',
    'garhi harsaru': 'sector 95',
    'dhankot': 'sector 102',
    'naharpur rupa': 'sector 33',
    'carterpuri village': 'sector 23',

    # Junctions
    'iffco chowk': 'sector 29',
    'rajiv chowk': 'sector 33',

    # Residential
    'ashok vihar': 'sector 5',
    'ashok vihar phase i': 'sector 5',
    'ashok vihar phase 2': 'sector 5',
    'ashok vihar phase 3': 'sector 5',
    'ashok vihar phase 3 extension': 'sector 5',
    'block h ashok vihar phase iii extension': 'sector 5',

    'surya vihar': 'sector 21',
    'block a surya vihar': 'sector 21',

    'rajendra park': 'sector 105',
    'saroop garden rajendra park': 'sector 105',

    'park view': 'sector 48',

    # Builders
    'bptp': 'sector 37d',
    'ats marigold': 'sector 89a',

    # Manesar
    'imt manesar': 'sector 1 imt',
    'manesar': 'sector 1 imt'
}

In [118]:
df['sector'] = df['sector'].replace(sector_map)

In [119]:
df['sector'].value_counts()

sector
sohna                                                        163
sector 102                                                   122
sector 85                                                    110
sector 92                                                    104
sector 69                                                     94
sector 65                                                     92
sector 90                                                     90
sector 81                                                     90
sector 109                                                    88
sector 79                                                     84
sector 48                                                     71
sector 83                                                     69
sector 37d                                                    69
sector 86                                                     67
sector 50                                                     66
sector 104                                                    66
sector 23                                                     63
sector 95                                                     61
sector 56                                                     61
sector 107                                                    60
sector 108                                                    59
sector 89                                                     56
sector 43                                                     55
sector 70a                                                    54
sector 70                                                     53
sector 37c                                                    53
sector 49                                                     52
sector 84                                                     51
sector-33 sohna                                               51
sector 26                                                     51
sector 67                                                     48
sector 66                                                     46
sector 103                                                    45
sector 25                                                     44
sector 113                                                    43
sector 61                                                     42
sector 82                                                     42
sector 106                                                    40
sector 5                                                      35
sector 28                                                     34
sector 99a                                                    32
sector 54                                                     31
sector 68                                                     30
sector 72                                                     29
sector 77                                                     29
sector 53                                                     28
sector 24                                                     28
sector 71                                                     27
laxman vihar                                                  27
sector 33                                                     26
sector 112                                                    24
sector 57                                                     24
sector 111                                                    24
sector 110                                                    23
sector 14                                                     23
sector 88a                                                    23
sector 67a                                                    22
sector 82a                                                    20
sector 105                                                    20
sector 22                                                     20
sector 2                                                      19
sector 78                                                     19
sector 47                                                     19
sector 74                                                     18
sector 63a                                                    18
sector 91                                                     17
sector 62                                                     17
sector 99                                                     16
sector 60                                                     15
sector 63                                                     15
sector 1 imt manesar                                          14
sector 3                                                      14
sector 76                                                     14
sector 52                                                     14
sector 55                                                     14
sector 36a                                                    13
laxman vihar phase 2                                          13
sector 46                                                     13
sector 93                                                     12
sector 38                                                     12
sector 31                                                     12
sector 39                                                     12
sector 59                                                     11
sector 9a                                                     11
sector 41                                                     11
sector 7                                                      10
sector 45                                                     10
sector 1a imt manesar                                         10
sector 95a                                                     9
sector 58                                                      9
sector 40                                                      9
sector 1 imt                                                   9
sector 51                                                      9
sector 4                                                       9
sector 10a                                                     8
sector 21                                                      8
sector 89 a                                                    8
new colony                                                     7
mianwali colony                                                7
sector 36 sohna                                                7
sector 11                                                      7
surat nagar 1                                                  7
jacobpura                                                      6
rajiv nagar                                                    6
sector 1                                                       6
jyoti park                                                     6
dayanand colony                                                5
subhash nagar                                                  5
sector 23a                                                     5
saraswati vihar                                                5
arjun nagar                                                    5
chakkarpur                                                     5
sector 30                                                      5
sector 80                                                      5
ansal plaza                                                    5
sector 9                                                       5
vishnu garden                                                  4
new                                                            4
bhim nagar                                                     4
sector 36                                                      4
sector 12                                                      4
ravi nagar                                                     4
sector 12a                                                     4
krishna colony                                                 4
shivpuri                                                       4
baldev nagar                                                   4
sector 17                                                      4
adarsh nagar                                                   4
devilal colony                                                 4
sector 3a                                                      4
shivaji nagar                                                  4
dharam colony                                                  4
madanpuri                                                      4
sector 6                                                       4
patel nagar                                                    3
sector 17a                                                     3
laxmi garden                                                   3
sector 27                                                      3
sector 42                                                      3
sector 88b                                                     3
sector 73                                                      3
sector 15                                                      3
shakti nagar                                                   3
prem nagar                                                     3
sector 110 a                                                   3
sector 17b                                                     3
sector 8                                                       3
gandhi nagar                                                   3
shanti nagar                                                   2
sector 29                                                      2
sector-2 sohna                                                 2
sector 15 part 2                                               2
new basti                                                      2
mohan nagar                                                    2
west rajiv nagar                                               2
samaspur                                                       2
farukhnagar                                                    2
lajpat nagar                                                   2
surat nagar phase 2                                            2
, delhi ncr                                                    2
sector 37                                                      2
surat nagar                                                    2
hira nagar                                                     2
sheetla colony                                                 2
sector 32                                                      2
sector 15 part 1                                               2
sector-11 sohna                                                2
pratap nagar                                                   2
nars                                                           2
shankar vihar                                                  2
bissar                                                         2
bhawani enclave                                                2
manohar nagar                                                  2
acharya puri                                                   2
sector 10                                                      2
sai kunj                                                       1
urban estate, sector 5                                         1
sec 3 bhim vihar part 1 bhimgher kheri                         1
ram nagar                                                      1
kheri                                                          1
begampur khatola                                               1
hno 13 sagar enclave sura                                      1
sector 20                                                      1
new colony, sector 7                                           1
devi lal colony gali no 12 gurgaon nr omkar public school      1
sadar bazar                                                    1
b1 block sector 57                                             1
sector 89a                                                     1
garauli kalan                                                  1
sector-5 sheetla colony                                        1
mahavir pura                                                   1
laxmna vihar, phase 2                                          1
om nagar                                                       1
ravi nager basai road                                          1
sector 4 urban estate                                          1
new jyoti park                                                 1
gopal nagar, garhi ghasita, sonipat                            1
lucknow                                                        1
bhimgarh kheri phase 3                                         1
tekchand nagar                                                 1
near sector 1 market                                           1
near nand hospital                                             1
old delhi road, opp sector-14                                  1
sector 21a faridabad                                           1
anand garden, sector-105                                       1
sector 5 chowk                                                 1
sultanpur                                                      1
hsiidc plot sector 1 imt manesar                               1
vir nagar                                                      1
sector-7 hous                                                  1
godrej aria , sector 79 ,                                      1
rattan garden                                                  1
shivji park colony                                             1
jacobpura near sadar bazar                                     1
alipur                                                         1
sector-5 sohna                                                 1
sector 9b                                                      1
saraswati enclave                                              1
bhora kalan                                                    1
sector 17c                                                     1
damdma                                                         1
laxman vihar, railway road,                                    1
mahalaxmi garden, rajendra place                               1
block g sector-57                                              1
civil l                                                        1
sector 13                                                      1
jat colony,fazilpur/taj nagar road                             1
sector 37b                                                     1
part 3 sector 5                                                1
sector-35 sohna                                                1
near euro                                                      1
huda saraswati vihar                                           1
rajiv colony                                                   1
sector 37a                                                     1
Name: count, dtype: int64

In [120]:
sector_normalization_map = {
    'sector-5 sheetla colony': 'sector 5',

    'sector 89 a': 'sector 89',
    'sector 89a': 'sector 89',

    'sector 110 a': 'sector 110',

    'sector 17a': 'sector 17',
    'sector 17b': 'sector 17',
    'sector 17c': 'sector 17',

    'sector 37a': 'sector 37',
    'sector 37b': 'sector 37',
    'sector 37c': 'sector 37',
    'sector 37d': 'sector 37',

    'sector 36a': 'sector 36',

    'sector 63a': 'sector 63',

    'sector 67a': 'sector 67',

    'sector 70a': 'sector 70',

    'sector 82a': 'sector 82',

    'sector 88a': 'sector 88',
    'sector 88b': 'sector 88',

    'sector 95a': 'sector 95',

    'sector 99a': 'sector 99',

    'sector 1 imt': 'sector 1',
    'sector 1 imt manesar': 'sector 1',
    'sector 1a imt manesar': 'sector 1',

    'sector 9a': 'sector 9',
    'sector 9b': 'sector 9',

    'sector 10a': 'sector 10',

    'sector 12a': 'sector 12',

    'sector 21a': 'sector 21',

    'sector 23a': 'sector 23',
    'sector-33 sohna': 'sector 33',
    'sector-2 sohna': 'sector 2',
    'sector-11 sohna': 'sector 11',
    'sector-35 sohna': 'sector 35',
    'sector-5 sohna': 'sector 5',

    'sector 36 sohna': 'sector 36',

    'sector 3a': 'sector 3',

    'sector 15 part 1': 'sector 15',
    'sector 15 part 2': 'sector 15',

    'new colony, sector 7': 'sector 7',
    'urban estate, sector 5': 'sector 5',
    'b1 block sector 57': 'sector 57',
    'sector 4 urban estate': 'sector 4',
    'old delhi road, opp sector-14': 'sector 14',
    'hsiidc plot sector 1 imt manesar': 'sector 1',
    'godrej aria , sector 79 ,': 'sector 79',
    'sector 5 chowk': 'sector 5',
    'sector-7 hous': 'sector 7',
    'block g sector-57': 'sector 57',
    'anand garden, sector-105': 'sector 105',
    'part 3 sector 5': 'sector 5',
    'sector 21a faridabad': 'sector 21'
}

In [121]:
df['sector'] = df['sector'].replace(sector_normalization_map)
df['sector'] = df['sector'].replace(sector_map)

In [122]:
df['sector'].value_counts()

sector
sohna                                                        163
sector 37                                                    126
sector 102                                                   122
sector 85                                                    110
sector 70                                                    107
sector 92                                                    104
sector 69                                                     94
sector 65                                                     92
sector 90                                                     90
sector 81                                                     90
sector 109                                                    88
sector 79                                                     85
sector 33                                                     77
sector 48                                                     71
sector 95                                                     70
sector 67                                                     70
sector 83                                                     69
sector 23                                                     68
sector 86                                                     67
sector 50                                                     66
sector 104                                                    66
sector 89                                                     65
sector 82                                                     62
sector 56                                                     61
sector 107                                                    60
sector 108                                                    59
sector 43                                                     55
sector 49                                                     52
sector 84                                                     51
sector 26                                                     51
sector 99                                                     48
sector 66                                                     46
sector 103                                                    45
sector 25                                                     44
sector 113                                                    43
sector 61                                                     42
sector 5                                                      40
sector 106                                                    40
sector 1                                                      40
sector 28                                                     34
sector 63                                                     33
sector 54                                                     31
sector 68                                                     30
sector 72                                                     29
sector 77                                                     29
sector 24                                                     28
sector 53                                                     28
laxman vihar                                                  27
sector 71                                                     27
sector 57                                                     26
sector 110                                                    26
sector 88                                                     26
sector 112                                                    24
sector 14                                                     24
sector 111                                                    24
sector 36                                                     24
sector 105                                                    21
sector 2                                                      21
sector 22                                                     20
sector 47                                                     19
sector 78                                                     19
sector 74                                                     18
sector 3                                                      18
sector 91                                                     17
sector 62                                                     17
sector 9                                                      17
sector 60                                                     15
sector 55                                                     14
sector 52                                                     14
sector 76                                                     14
laxman vihar phase 2                                          13
sector 46                                                     13
sector 38                                                     12
sector 7                                                      12
sector 93                                                     12
sector 39                                                     12
sector 31                                                     12
sector 59                                                     11
sector 41                                                     11
sector 17                                                     11
sector 4                                                      10
sector 10                                                     10
sector 45                                                     10
sector 21                                                      9
sector 51                                                      9
sector 11                                                      9
sector 40                                                      9
sector 58                                                      9
sector 12                                                      8
new colony                                                     7
mianwali colony                                                7
sector 15                                                      7
surat nagar 1                                                  7
jyoti park                                                     6
rajiv nagar                                                    6
jacobpura                                                      6
arjun nagar                                                    5
dayanand colony                                                5
subhash nagar                                                  5
sector 80                                                      5
sector 30                                                      5
saraswati vihar                                                5
chakkarpur                                                     5
ansal plaza                                                    5
bhim nagar                                                     4
vishnu garden                                                  4
adarsh nagar                                                   4
new                                                            4
shivpuri                                                       4
krishna colony                                                 4
devilal colony                                                 4
ravi nagar                                                     4
baldev nagar                                                   4
dharam colony                                                  4
madanpuri                                                      4
sector 6                                                       4
shivaji nagar                                                  4
sector 8                                                       3
patel nagar                                                    3
sector 27                                                      3
sector 42                                                      3
shakti nagar                                                   3
laxmi garden                                                   3
gandhi nagar                                                   3
prem nagar                                                     3
sector 73                                                      3
west rajiv nagar                                               2
new basti                                                      2
farukhnagar                                                    2
lajpat nagar                                                   2
shanti nagar                                                   2
sector 29                                                      2
mohan nagar                                                    2
samaspur                                                       2
, delhi ncr                                                    2
surat nagar phase 2                                            2
nars                                                           2
hira nagar                                                     2
shankar vihar                                                  2
bhawani enclave                                                2
pratap nagar                                                   2
acharya puri                                                   2
surat nagar                                                    2
bissar                                                         2
sector 32                                                      2
manohar nagar                                                  2
sheetla colony                                                 2
kheri                                                          1
sadar bazar                                                    1
huda saraswati vihar                                           1
sai kunj                                                       1
sec 3 bhim vihar part 1 bhimgher kheri                         1
begampur khatola                                               1
ram nagar                                                      1
laxmna vihar, phase 2                                          1
mahavir pura                                                   1
sector 20                                                      1
om nagar                                                       1
ravi nager basai road                                          1
new jyoti park                                                 1
gopal nagar, garhi ghasita, sonipat                            1
lucknow                                                        1
bhimgarh kheri phase 3                                         1
tekchand nagar                                                 1
near sector 1 market                                           1
hno 13 sagar enclave sura                                      1
civil l                                                        1
devi lal colony gali no 12 gurgaon nr omkar public school      1
garauli kalan                                                  1
sultanpur                                                      1
vir nagar                                                      1
rattan garden                                                  1
shivji park colony                                             1
jacobpura near sadar bazar                                     1
saraswati enclave                                              1
alipur                                                         1
laxman vihar, railway road,                                    1
rajiv colony                                                   1
mahalaxmi garden, rajendra place                               1
bhora kalan                                                    1
damdma                                                         1
jat colony,fazilpur/taj nagar road                             1
sector 35                                                      1
near euro                                                      1
sector 13                                                      1
near nand hospital                                             1
Name: count, dtype: int64

In [123]:
a = df['sector'].value_counts()[df['sector'].value_counts() >= 3]
df = df[df['sector'].isin(a.index)]

In [124]:
df['sector'].value_counts()

sector
sohna                   163
sector 37               126
sector 102              122
sector 85               110
sector 70               107
sector 92               104
sector 69                94
sector 65                92
sector 81                90
sector 90                90
sector 109               88
sector 79                85
sector 33                77
sector 48                71
sector 95                70
sector 67                70
sector 83                69
sector 23                68
sector 86                67
sector 50                66
sector 104               66
sector 89                65
sector 82                62
sector 56                61
sector 107               60
sector 108               59
sector 43                55
sector 49                52
sector 84                51
sector 26                51
sector 99                48
sector 66                46
sector 103               45
sector 25                44
sector 113               43
sector 61                42
sector 1                 40
sector 5                 40
sector 106               40
sector 28                34
sector 63                33
sector 54                31
sector 68                30
sector 77                29
sector 72                29
sector 24                28
sector 53                28
sector 71                27
laxman vihar             27
sector 57                26
sector 88                26
sector 110               26
sector 14                24
sector 111               24
sector 36                24
sector 112               24
sector 105               21
sector 2                 21
sector 22                20
sector 47                19
sector 78                19
sector 74                18
sector 3                 18
sector 91                17
sector 62                17
sector 9                 17
sector 60                15
sector 52                14
sector 76                14
sector 55                14
laxman vihar phase 2     13
sector 46                13
sector 38                12
sector 31                12
sector 39                12
sector 93                12
sector 7                 12
sector 17                11
sector 41                11
sector 59                11
sector 4                 10
sector 10                10
sector 45                10
sector 40                 9
sector 21                 9
sector 51                 9
sector 11                 9
sector 58                 9
sector 12                 8
new colony                7
mianwali colony           7
sector 15                 7
surat nagar 1             7
jyoti park                6
jacobpura                 6
rajiv nagar               6
sector 30                 5
arjun nagar               5
saraswati vihar           5
chakkarpur                5
dayanand colony           5
subhash nagar             5
sector 80                 5
ansal plaza               5
krishna colony            4
bhim nagar                4
adarsh nagar              4
devilal colony            4
ravi nagar                4
shivaji nagar             4
baldev nagar              4
madanpuri                 4
sector 6                  4
dharam colony             4
shivpuri                  4
vishnu garden             4
new                       4
sector 73                 3
patel nagar               3
sector 42                 3
laxmi garden              3
sector 8                  3
shakti nagar              3
prem nagar                3
gandhi nagar              3
sector 27                 3
Name: count, dtype: int64

In [126]:
approx_sector_map = {

    'laxman vihar': 'sector 4',
    'laxman vihar phase 2': 'sector 4',

    'new colony': 'sector 7',

    'mianwali colony': 'sector 12',

    'surat nagar 1': 'sector 104',

    'jyoti park': 'sector 7',

    'jacobpura': 'sector 12',

    'rajiv nagar': 'sector 13',

    'arjun nagar': 'sector 8',

    'saraswati vihar': 'sector 28',

    'chakkarpur': 'sector 28',

    'dayanand colony': 'sector 6',

    'subhash nagar': 'sector 12',

    'ansal plaza': 'sector 23',

    'krishna colony': 'sector 7',

    'bhim nagar': 'sector 6',

    'adarsh nagar': 'sector 12',

    'devilal colony': 'sector 9',

    'ravi nagar': 'sector 9',

    'shivaji nagar': 'sector 11',

    'baldev nagar': 'sector 7',

    'madanpuri': 'sector 7',

    'dharam colony': 'sector 12',

    'shivpuri': 'sector 7',

    'vishnu garden': 'sector 105',

    'patel nagar': 'sector 15',

    'laxmi garden': 'sector 11',

    'shakti nagar': 'sector 11',

    'prem nagar': 'sector 12',

    'gandhi nagar': 'sector 14'
}

In [127]:
df['sector'] = df['sector'].replace(approx_sector_map)

In [128]:
df['sector'].value_counts()

sector
sohna         163
sector 37     126
sector 102    122
sector 85     110
sector 70     107
sector 92     104
sector 69      94
sector 65      92
sector 81      90
sector 90      90
sector 109     88
sector 79      85
sector 33      77
sector 23      73
sector 104     73
sector 48      71
sector 67      70
sector 95      70
sector 83      69
sector 86      67
sector 50      66
sector 89      65
sector 82      62
sector 56      61
sector 107     60
sector 108     59
sector 43      55
sector 49      52
sector 26      51
sector 84      51
sector 4       50
sector 99      48
sector 66      46
sector 103     45
sector 28      44
sector 25      44
sector 113     43
sector 61      42
sector 7       41
sector 106     40
sector 1       40
sector 5       40
sector 12      37
sector 63      33
sector 54      31
sector 68      30
sector 77      29
sector 72      29
sector 53      28
sector 24      28
sector 14      27
sector 71      27
sector 110     26
sector 88      26
sector 57      26
sector 9       25
sector 105     25
sector 111     24
sector 36      24
sector 112     24
sector 2       21
sector 22      20
sector 78      19
sector 11      19
sector 47      19
sector 3       18
sector 74      18
sector 62      17
sector 91      17
sector 60      15
sector 52      14
sector 76      14
sector 55      14
sector 6       13
sector 46      13
sector 39      12
sector 31      12
sector 93      12
sector 38      12
sector 59      11
sector 17      11
sector 41      11
sector 45      10
sector 10      10
sector 15      10
sector 21       9
sector 51       9
sector 40       9
sector 58       9
sector 8        8
sector 13       6
sector 30       5
sector 80       5
new             4
sector 73       3
sector 42       3
sector 27       3
Name: count, dtype: int64

In [130]:
df[df['sector'] == 'new']

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
781,4 BHK Flat in New Gurgaon,flat,dlf 76,new,4.00,11428.0,3500.0,Carpet area: 3500 (325.16 sq.m.),4,4,2,"study room,servant room","New Gurgaon, Gurgaon, Haryana",4.0,NaN,Jun 2027,"['Shri Balaji Hospital and Trauma Center', 'S....",This lovely 4 bhk apartment/flat in new gurgao...,"['6 Wardrobe', '1 Fridge', '8 Fan', '1 Exhaust...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...",NaN
2093,2 BHK Flat in New Gurgaon,flat,takshila heights sector 37 c,new,0.67,5583.0,1200.0,Super Built up area 1200(111.48 sq.m.),2,2,2,not available,"New Gurgaon, Gurgaon, Haryana",3.0,NaN,1 to 5 Year Old,"['Shri Balaji Hospital and Trauma Center', 'S....",Check out this 2 bhk apartment for sale in tak...,[],"['Lift(s)', 'Swimming Pool', 'Visitor Parking'...",NaN
2908,2 BHK Flat in New Gurgaon,flat,green court,new,0.38,5507.0,690.0,Carpet area: 690 (64.1 sq.m.),2,2,1,not available,"New Gurgaon, Gurgaon, Haryana",7.0,NaN,Under Construction,"['Ing bank ATM', 'Dcb bank ATM', 'Indus ind ba...",We are the proud owners of this 2 bhk apartmen...,[],"['Intercom Facility', 'Lift(s)', 'Maintenance ...",NaN
3744,4 BHK Flat in New Gurgaon,flat,sare homes,new,0.85,4786.0,1776.0,Super Built up area 1776(165 sq.m.),4,4,3,not available,"New Gurgaon, Gurgaon, Haryana",3.0,NaN,5 to 10 Year Old,"['Columbia Asia Hospital', 'Apex Multi Special...",Located in the popular residential address of ...,[],NaN,NaN

In [131]:
df.loc[2093,'sector'] = 'sector 37'
df.loc[3744,'sector'] = 'sector 92'
df.loc[2908,'sector'] = 'sector 90'
df.loc[781,'sector'] = 'sector 76'

In [132]:
df.shape

(3880, 21)

In [134]:
df.duplicated().sum()

np.int64(0)

In [135]:
df.head()

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,5 Bedroom House for sale in Sector 11 Gurgaon,house,independent,sector 11,4.00,19753.0,2025.0,Built Up area: 225 (188.13 sq.m.)Carpet area: ...,5,4,1,not available,"Sector 11, Sector 11 Gurgaon, Gurgaon, Haryana",2.0,North-East,undefined,"['Palam Vihar Vyapar kendra', 'Palam triangle'...","4 bath, furnished, overlooking garden/park, ma...","['1 Wardrobe', '1 Fan', '1 Light', 'No AC', 'N...",NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
2,4 BHK Flat in Sector 110 Gurgaon,flat,indiabulls enigma,sector 110,3.30,9850.0,3350.0,Super Built up area 3350(311.23 sq.m.),4,5,3,servant room,"N/a, Sector 110 Gurgaon, Gurgaon, Haryana",7.0,East,1 to 5 Year Old,"['Dwarka Sector 21 Metro Station', 'Gurgaon Dr...",Located in the popular residential address of ...,[],"['Security / Fire Alarm', 'Power Back-up', 'Fe...","['Environment4 out of 5', 'Lifestyle4 out of 5..."
3,3 BHK Flat in Sector 104 Gurgaon,flat,puri emerald bay,sector 104,2.30,9387.0,2450.0,Super Built up area 2450(227.61 sq.m.),3,4,3+,servant room,"N/a, Sector 104 Gurgaon, Gurgaon, Haryana",10.0,North-East,5 to 10 Year Old,"['Sector-21 Metro Dwarka', 'Gurgaon Dreamz Mal...",This 3 bhk apartment is available for sale in ...,[],"['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Green Area5 out of 5', 'Construction5 out of..."
4,4 Bedroom House for sale in Nirvana Country,house,nirvana cedar crest,sector 50,3.99,8866.0,4500.0,Plot area 4500(418.06 sq.m.),4,5,3+,"pooja room,servant room","Nirvana Country, Gurgaon, Haryana",4.0,North-East,0 to 1 Year Old,"['Radhakrishna Shani Mandir', 'Standard charte...",This is an newly constructed villa located in ...,"['4 Geyser', '9 Light', '1 AC', '1 Modular Kit...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
5,3 BHK Flat in Sector 37D Gurgaon,flat,bptp terra,sector 37,1.45,8006.0,1811.0,Super Built up area 1811(168.25 sq.m.)Built Up...,3,3,3,not available,"803, Sector 37D Gurgaon, Gurgaon, Haryana",8.0,South-East,1 to 5 Year Old,"['Airia Mall', 'Dwarka Expressway', 'Golf Cour...",This lovely 3 bhk apartment/flat in sector 37d...,"['5 AC', '1 Chimney', '1 Modular Kitchen', '2 ...","['Centrally Air Conditioned', 'Water purifier'...","['Green Area4.5 out of 5', 'Construction4.5 ou..."

In [136]:
df.drop(columns=['property_name', 'address', 'description', 'rating'],inplace=True)

In [137]:
df.sample(5)

,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,floorNum,facing,agePossession,nearbyLocations,furnishDetails,features
475,flat,shree vardhman victoria,sector 70,1.80,9230.0,1950.0,Super Built up area 1950(181.16 sq.m.),3,3,3+,others,10.0,North-East,0 to 1 Year Old,"['Airia Mall', 'Golf Course Extn Road', 'Sohna...","['4 Wardrobe', '1 Exhaust Fan', '9 Light', '1 ...","['Feng Shui / Vaastu Compliant', 'Security / F..."
1239,flat,puri diplomatic greens,sector 111,3.50,11864.0,2950.0,Super Built up area 2950(274.06 sq.m.)Built Up...,4,5,3+,servant room,10.0,North-East,1 to 5 Year Old,"['Dwarka Sector 21 Metro Station', 'Gurgaon Dr...","['4 Wardrobe', '6 Fan', '1 Exhaust Fan', '5 Ge...","['Feng Shui / Vaastu Compliant', 'Security / F..."
25,house,independent,sector 26,18.40,1859.0,98978.0,Plot area 502(419.74 sq.m.)Carpet area: 11000 ...,6,8,3+,"pooja room,store room,servant room",4.0,South,1 to 5 Year Old,"['Guru dronacharya metro station', 'Dlf phase ...","['6 Wardrobe', '16 Fan', '1 Exhaust Fan', '8 G...","['Feng Shui / Vaastu Compliant', 'Private Gard..."
2602,flat,aipl the peaceful homes,sector 70,2.40,11162.0,2150.0,Super Built up area 2150(199.74 sq.m.),3,3,3,servant room,11.0,South-West,1 to 5 Year Old,"['Airia Mall', 'Golf Corse Ext. Rd.', 'Nationa...","['5 Fan', '3 Geyser', '6 Light', '3 AC', 'No B...","['Security / Fire Alarm', 'Power Back-up', 'Fe..."
128,flat,cghs airport apartment,sector 47,1.65,7857.0,2100.0,Super Built up area 2100(195.1 sq.m.)Carpet ar...,3,3,3,others,1.0,North-East,10+ Year Old,"['Rajiv Chowk Mosque', 'Standard chartered ATM...","['5 Fan', '1 Exhaust Fan', '4 Geyser', '10 Lig...","['Security / Fire Alarm', 'Feng Shui / Vaastu ..."

In [ ]:
# feature engineering required -> areaWithType, additionalRoom, facing, agePossession, furnishDetails, features

In [153]:
df.duplicated().sum()

np.int64(123)

In [156]:
df.drop_duplicates(keep='first',inplace=True)

In [159]:
df.shape

(3757, 17)

In [160]:
df.to_csv('gurgaon_properties_cleaned_v1.csv',index=False)